### PR TITLE
Updated illustrated message and drop zone tokens

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Marked the following tokens as deprecated, fixed the type to `fontSizes`, and pointed the values to the new tokens replacing them:
  - `illustrated-message-title-size`
  - `illustrated-message-cjk-title-size`
  - `illustrated-message-body-size`
  - `drop-zone-title-size`
  - `drop-zone-cjk-title-size`
  - `drop-zone-body-size`
- Added illustrated message font-size tokens in small, medium, and large sizes 
- Added drop zone font-size tokens
- Updated `drop-zone-border-dash-gap` token value

## Motivation and context

- The previous tokens had the incorrect types. By fixing the type, they can reference the updated tokens that are replacing them.
- Illustrated message now has three sizes (S, M, L) in Spectrum 2 to cover a wider range of use cases
- Component font size tokens now specify `font` in the token name

## Related issue

[SDS-13386](https://jira.corp.adobe.com/browse/SDS-13386)
[SDS-13387](https://jira.corp.adobe.com/browse/SDS-13387)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [x] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8855079339)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-body-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-cjk-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.illustrated-message-small-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (17) illustrated-message-small-title-font-size/desktop, illustrated-message-small-title-font-size/mobile, illustrated-message-small-cjk-title-font-size/desktop, illustrated-message-small-cjk-title-font-size/mobile, illustrated-message-medium-title-font-size/desktop, illustrated-message-medium-title-font-size/mobile, illustrated-message-medium-cjk-title-font-size/desktop, illustrated-message-medium-cjk-title-font-size/mobile, illustrated-message-large-title-font-size/desktop, illustrated-message-large-title-font-size/mobile, illustrated-message-large-cjk-title-font-size/desktop, illustrated-message-large-cjk-title-font-size/mobile, illustrated-message-small-body-font-size, illustrated-message-medium-body-font-size/desktop, illustrated-message-medium-body-font-size/mobile, illustrated-message-large-body-font-size/desktop, illustrated-message-large-body-font-size/mobile
MODIFIED TOKENS: (3) illustrated-message-body-size, illustrated-message-cjk-title-size, illustrated-message-title-size
DEPRECATED TOKENS: (6) illustrated-message-title-size/desktop, illustrated-message-title-size/mobile, illustrated-message-cjk-title-size/desktop, illustrated-message-cjk-title-size/mobile, illustrated-message-body-size/desktop, illustrated-message-body-size/mobile
CHANGED VALUES: (3) illustrated-message-body-size/desktop, illustrated-message-cjk-title-size/desktop, illustrated-message-title-size/desktop impacting 6 tokens
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8855148269)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-body-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-cjk-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.illustrated-message-small-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (20) illustrated-message-small-title-font-size/desktop, illustrated-message-small-title-font-size/mobile, illustrated-message-small-cjk-title-font-size/desktop, illustrated-message-small-cjk-title-font-size/mobile, illustrated-message-medium-title-font-size/desktop, illustrated-message-medium-title-font-size/mobile, illustrated-message-medium-cjk-title-font-size/desktop, illustrated-message-medium-cjk-title-font-size/mobile, illustrated-message-large-title-font-size/desktop, illustrated-message-large-title-font-size/mobile, illustrated-message-large-cjk-title-font-size/desktop, illustrated-message-large-cjk-title-font-size/mobile, illustrated-message-small-body-font-size, illustrated-message-medium-body-font-size/desktop, illustrated-message-medium-body-font-size/mobile, illustrated-message-large-body-font-size/desktop, illustrated-message-large-body-font-size/mobile, drop-zone-title-font-size, drop-zone-cjk-title-font-size, drop-zone-body-font-size
MODIFIED TOKENS: (3) illustrated-message-body-size, illustrated-message-cjk-title-size, illustrated-message-title-size
DEPRECATED TOKENS: (9) illustrated-message-title-size/desktop, illustrated-message-title-size/mobile, illustrated-message-cjk-title-size/desktop, illustrated-message-cjk-title-size/mobile, illustrated-message-body-size/desktop, illustrated-message-body-size/mobile, drop-zone-title-size, drop-zone-cjk-title-size, drop-zone-body-size
CHANGED VALUES: (7) drop-zone-body-size, drop-zone-border-dash-gap, drop-zone-cjk-title-size, drop-zone-title-size, illustrated-message-body-size/desktop, illustrated-message-cjk-title-size/desktop, illustrated-message-title-size/desktop
```
</p></details>

TEST COMPLETE

**Review by nabuhasan — APPROVED** [review]
Approved, looks great!

**Review by karstens — APPROVED** [review]
Looks good to me, too. Thank you 🌻

**Comment by karstens** [comment]
@GarthDB This is ready to merge.

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8915120902)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-body-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-cjk-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 illustrated-message-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-small-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.illustrated-message-small-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-medium-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.illustrated-message-large-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.illustrated-message-large-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-cjk-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.drop-zone-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (20) illustrated-message-small-title-font-size/desktop, illustrated-message-small-title-font-size/mobile, illustrated-message-small-cjk-title-font-size/desktop, illustrated-message-small-cjk-title-font-size/mobile, illustrated-message-medium-title-font-size/desktop, illustrated-message-medium-title-font-size/mobile, illustrated-message-medium-cjk-title-font-size/desktop, illustrated-message-medium-cjk-title-font-size/mobile, illustrated-message-large-title-font-size/desktop, illustrated-message-large-title-font-size/mobile, illustrated-message-large-cjk-title-font-size/desktop, illustrated-message-large-cjk-title-font-size/mobile, illustrated-message-small-body-font-size, illustrated-message-medium-body-font-size/desktop, illustrated-message-medium-body-font-size/mobile, illustrated-message-large-body-font-size/desktop, illustrated-message-large-body-font-size/mobile, drop-zone-title-font-size, drop-zone-cjk-title-font-size, drop-zone-body-font-size
MODIFIED TOKENS: (3) illustrated-message-body-size, illustrated-message-cjk-title-size, illustrated-message-title-size
DEPRECATED TOKENS: (9) illustrated-message-title-size/desktop, illustrated-message-title-size/mobile, illustrated-message-cjk-title-size/desktop, illustrated-message-cjk-title-size/mobile, illustrated-message-body-size/desktop, illustrated-message-body-size/mobile, drop-zone-title-size, drop-zone-cjk-title-size, drop-zone-body-size
CHANGED VALUES: (7) drop-zone-body-size, drop-zone-border-dash-gap, drop-zone-cjk-title-size, drop-zone-title-size, illustrated-message-body-size/desktop, illustrated-message-cjk-title-size/desktop, illustrated-message-title-size/desktop
```
</p></details>

UPDATED SET SCHEMAS: 1

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-component.json`

SYNC COMPLETE
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/128)

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/337)

**Pull request merged**
