### PR TITLE
S2 Color - Deprecation of negative-subdued-background tokens

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description
Marked the the following tokens in Tokens Studio for deprecation:

- negative-subdued-background-color-default ( --> points to negative-subtle-background-color-default)
- negative-subdued-background-color-hover
- negative-subdued-background-color-down
- negative-subdued-background-color-key-focus

Changes were made in light and dark sets and variables were synced in S2/Variables with the latest updates. 

For more information, [view Jira ticket](https://jira.corp.adobe.com/browse/SDS-13415). 

## Motivation and context
These tokens were deprecated because the tag "error" variant has been deprecated and are no longer needed in the system. A new "subtle" token has been added for the in-line alert use case.

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9402597159)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.semantic.negative-subdued.🚫 default
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) negative-subdued-background-color-default/dark
MODIFIED TOKENS: (1) negative-subdued-background-color-default/light
DEPRECATED TOKENS: (4) negative-subdued-background-color-default, negative-subdued-background-color-hover, negative-subdued-background-color-down, negative-subdued-background-color-key-focus
CHANGED VALUES: (1) negative-subdued-background-color-default
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9402708861)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.semantic.🚫 negative-subdued.default
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) negative-subdued-background-color-default/dark
MODIFIED TOKENS: (1) negative-subdued-background-color-default/light
DEPRECATED TOKENS: (4) negative-subdued-background-color-default, negative-subdued-background-color-hover, negative-subdued-background-color-down, negative-subdued-background-color-key-focus
CHANGED VALUES: (1) negative-subdued-background-color-default
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9402768584)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
DEPRECATED TOKENS: (4) negative-subdued-background-color-default, negative-subdued-background-color-hover, negative-subdued-background-color-down, negative-subdued-background-color-key-focus
CHANGED VALUES: (1) negative-subdued-background-color-default
```
</p></details>

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
Looks good, thank you!

**Review by karstens — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
