### PR TITLE
Updated thumbnail size tokens and added new tokens

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Updated thumbnail size tokens, including all sizes from `75` to `1000`
- Added new thumbnail tokens:
  - `thumbnail-corner-radius`
  - `thumbnail-opacity-checkerboard-square-size`

## Motivation and context

- Thumbnail: updated sizes in order for opacity checkerboards to translate better in implementation. 
  - ⚠️ Important note: Accepting updates from this release will update the thumbnail sizes. The change in size is no more than 4 px. In some cases, you may want to relink to a new size. View the migration guide below to find the closest recommended size:

| Former thumbnail size | Available thumbnail size |
|:-----------------------|:------------------------------------------|
| size 50 (16 x 16)     | size 50 (16 x 16)                        |
| size 75 (18 x 18)     | size 75 (20 x 20)                        |
| size 100 (20 x 20)    | size 75 (20 x 20)                        |
| size 200 (22 x 22)    | size 100 (24 x 24)                       |
| size 300 (26 x 26)    | size 200 (28 x 28)                       |
| size 400 (28 x 28)    | size 200 (28 x 28)                       |
| size 500 (32 x 32)    | size 300 (32 x 32)                       |
| size 600 (36 x 36)    | size 400 (36 x 36)                       |
| size 700 (40 x 40)    | size 500 (40 x 40)                       |
| size 800 (44 x 44)    | size 600 (44 x 44)                       |
| size 900 (50 x 50)    | size 700 (48 x 48) or size 800 (52 x 52) |
| size 1000 (56 x 56)   | size 900 (56 x 56)                       |
| --                    | size 1000 (64 x 64)                      |

## Related issue

[SDS-13436](https://jira.corp.adobe.com/browse/SDS-13436)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [x] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9620358770)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.thumbnail-opacity-checkerboard-square-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.thumbnail-corner-radius
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (6) contextual-help-body-font-size/desktop, contextual-help-title-font-size/desktop, contextual-help-body-font-size/mobile, contextual-help-title-font-size/mobile, thumbnail-opacity-checkerboard-square-size, thumbnail-corner-radius
MODIFIED TOKENS: (2) contextual-help-body-size, contextual-help-title-size
DEPRECATED TOKENS: (6) contextual-help-title-size/desktop, contextual-help-title-size/mobile, contextual-help-body-size/desktop, contextual-help-body-size/mobile, contextual-help-body-size, contextual-help-title-size
CHANGED VALUES: (24) thumbnail-size-75/desktop, thumbnail-size-100/desktop, thumbnail-size-200/desktop, thumbnail-size-300/desktop, thumbnail-size-400/desktop, thumbnail-size-500/desktop, thumbnail-size-600/desktop, thumbnail-size-700/desktop, thumbnail-size-800/desktop, thumbnail-size-900/desktop, thumbnail-size-1000/desktop, thumbnail-size-75/mobile, thumbnail-size-100/mobile, thumbnail-size-200/mobile, thumbnail-size-300/mobile, thumbnail-size-400/mobile, thumbnail-size-500/mobile, thumbnail-size-600/mobile, thumbnail-size-700/mobile, thumbnail-size-800/mobile, thumbnail-size-900/mobile, thumbnail-size-1000/mobile, contextual-help-body-size/desktop, contextual-help-title-size/desktop impacting 13 tokens
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
@GarthDB I marked this as `major` since it could potentially cause layout shifts. Let me know if it should be `minor` instead.
Also, I tried with the markdown table but feel free to edit if there's ways to improve!

**Review by nabuhasan — APPROVED** [review]
Looks great!

**Review by karstens — APPROVED** [review]
looks good to me 👍

**Comment by GarthDB** [comment]
I think major fits this sort of change.

**Pull request merged**
