### PR TITLE
Added CODEOWNERS file

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

I'm adding a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to make it easier to require approvals from 2 or more people before it is able to be merged.

Currently, there is support for requiring a specific number of approvals from different teams (like one from engineering and one from design); until that functionality is added to GitHub-protected branches, I just added the single team, [@adobe/spectrum-design-data](https://github.com/orgs/adobe/teams/spectrum-design-data).

## Motivation and context

Just want to make sure we get full approval before merging.

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)</li>
<li> [x] Chore/tests/architecture (does not impact data, just infrastructure changes</li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by GarthDB** [comment]
There is also the option to have PRs automatically merged when all requirements are met, In the case of the current rules, that means at least 2 approvals and the Adobe CLA Signed.

image

**Review by lynnhao — APPROVED** [review]
Thank you Garth!

**Comment by karstens** [comment]
@GarthDB @lynnhao I like it, just would not enable "auto-merge" until we can control the two approvals from two sides (eng & design).

**Review by karstens — APPROVED** [review]

**Comment by mrcjhicks** [comment]
We have a git action that creates branches, PRs, and merges them automatically... which restrictions will need to carve out an exception for.

**Review by mrcjhicks — CHANGES_REQUESTED** [review]
We need to carve out an exception for PRs created by the sync git action to allow it to add UUIDs to token definitions.

Edit: we worked around this in the git action, instead - we're good!

**Review by mrcjhicks — APPROVED** [review]

**Pull request merged**
