### PR TITLE
Updated S2 Table tokens

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description

Updated tokens for the S2 Table component in **S2 layout.component** set. 

- table-column-header-row-top-to-text-medium
- table-row-top-to-text-medium-regular
- table-row-bottom-to-text-medium-regular
- table-row-top-to-text-medium-spacious
- table-header-row-checkbox-to-top-medium
- table-row-checkbox-to-top-medium-compact
- table-row-checkbox-to-top-medium-regular
- table-row-checkbox-to-top-medium-spacious

Added new token to the **S2 layout** set: 
- side-focus-indicator

Tokens changes are reflected in both desktop and mobile sets. 

## Motivation and context
Table component is being formalized as a Spectrum 2 component. These updated tokens define the design data needed for implementation.

## Related issue
For more information, [view Jira ticket](https://jira.corp.adobe.com/browse/SDS-13557).

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10206902848)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.side-focus-indicator
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) side-focus-indicator
CHANGED VALUES: (12) table-column-header-row-top-to-text-medium/desktop, table-header-row-checkbox-to-top-medium/desktop, table-row-bottom-to-text-medium-regular/desktop, table-row-checkbox-to-top-medium-compact/desktop, table-row-checkbox-to-top-medium-regular/desktop, table-row-checkbox-to-top-medium-spacious/desktop, table-row-top-to-text-medium-regular/desktop, table-header-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-medium-compact/mobile, table-row-checkbox-to-top-medium-regular/mobile, table-row-checkbox-to-top-medium-spacious/mobile, table-row-top-to-text-medium-spacious/mobile impacting 8 tokens
```
</p></details>

TEST COMPLETE

**Review by PaliwalSparsh — APPROVED** [review]
LGTM!

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10408858079)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.standard-panel.gripper-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.side-focus-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (41) side-focus-indicator, table-row-bottom-to-text-extra-large/desktop, table-row-bottom-to-text-large/desktop, table-row-bottom-to-text-medium/desktop, table-row-bottom-to-text-small/desktop, table-row-checkbox-to-top-extra-large/desktop, table-row-checkbox-to-top-large/desktop, table-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-small/desktop, table-row-height-extra-large/desktop, table-row-height-large/desktop, table-row-height-medium/desktop, table-row-height-small/desktop, table-row-top-to-text-extra-large/desktop, table-row-top-to-text-large/desktop, table-row-top-to-text-medium/desktop, table-row-top-to-text-small/desktop, table-thumbnail-to-top-minimum-extra-large/desktop, table-thumbnail-to-top-minimum-large/desktop, table-thumbnail-to-top-minimum-medium/desktop, table-thumbnail-to-top-minimum-small/desktop, table-row-bottom-to-text-extra-large/mobile, table-row-bottom-to-text-large/mobile, table-row-bottom-to-text-medium/mobile, table-row-bottom-to-text-small/mobile, table-row-checkbox-to-top-extra-large/mobile, table-row-checkbox-to-top-large/mobile, table-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-small/mobile, table-row-height-extra-large/mobile, table-row-height-large/mobile, table-row-height-medium/mobile, table-row-height-small/mobile, table-row-top-to-text-extra-large/mobile, table-row-top-to-text-large/mobile, table-row-top-to-text-medium/mobile, table-row-top-to-text-small/mobile, table-thumbnail-to-top-minimum-extra-large/mobile, table-thumbnail-to-top-minimum-large/mobile, table-thumbnail-to-top-minimum-medium/mobile, table-thumbnail-to-top-minimum-small/mobile
MODIFIED TOKENS: (1) standard-panel-gripper-color-drag
RENAMED TOKENS: (20) table-row-bottom-to-text-extra-large-regular, table-row-bottom-to-text-large-regular, table-row-bottom-to-text-medium-regular, table-row-bottom-to-text-small-regular, table-row-checkbox-to-top-extra-large-regular, table-row-checkbox-to-top-large-regular, table-row-checkbox-to-top-medium-regular, table-row-checkbox-to-top-small-regular, table-row-height-extra-large-regular, table-row-height-large-regular, table-row-height-medium-regular, table-row-height-small-regular, table-row-top-to-text-extra-large-regular, table-row-top-to-text-large-regular, table-row-top-to-text-medium-regular, table-row-top-to-text-small-regular, table-thumbnail-to-top-minimum-extra-large-regular, table-thumbnail-to-top-minimum-large-regular, table-thumbnail-to-top-minimum-medium-regular, table-thumbnail-to-top-minimum-small-regular
DEPRECATED TOKENS: (41) standard-panel-gripper-color-drag/dark, table-row-height-small-regular/desktop, table-row-height-small-regular/mobile, table-row-height-medium-regular/desktop, table-row-height-medium-regular/mobile, table-row-height-large-regular/desktop, table-row-height-large-regular/mobile, table-row-height-extra-large-regular/desktop, table-row-height-extra-large-regular/mobile, table-row-top-to-text-small-regular/desktop, table-row-top-to-text-small-regular/mobile, table-row-top-to-text-medium-regular/desktop, table-row-top-to-text-medium-regular/mobile, table-row-top-to-text-large-regular/desktop, table-row-top-to-text-large-regular/mobile, table-row-top-to-text-extra-large-regular/desktop, table-row-top-to-text-extra-large-regular/mobile, table-row-bottom-to-text-small-regular/desktop, table-row-bottom-to-text-small-regular/mobile, table-row-bottom-to-text-medium-regular/desktop, table-row-bottom-to-text-medium-regular/mobile, table-row-bottom-to-text-large-regular/desktop, table-row-bottom-to-text-large-regular/mobile, table-row-bottom-to-text-extra-large-regular/desktop, table-row-bottom-to-text-extra-large-regular/mobile, table-row-checkbox-to-top-small-regular/desktop, table-row-checkbox-to-top-small-regular/mobile, table-row-checkbox-to-top-medium-regular/desktop, table-row-checkbox-to-top-medium-regular/mobile, table-row-checkbox-to-top-large-regular/desktop, table-row-checkbox-to-top-large-regular/mobile, table-row-checkbox-to-top-extra-large-regular/desktop, table-row-checkbox-to-top-extra-large-regular/mobile, table-thumbnail-to-top-minimum-small-regular/desktop, table-thumbnail-to-top-minimum-small-regular/mobile, table-thumbnail-to-top-minimum-medium-regular/desktop, table-thumbnail-to-top-minimum-medium-regular/mobile, table-thumbnail-to-top-minimum-large-regular/desktop, table-thumbnail-to-top-minimum-large-regular/mobile, table-thumbnail-to-top-minimum-extra-large-regular/desktop, table-thumbnail-to-top-minimum-extra-large-regular/mobile
CHANGED VALUES: (8) table-column-header-row-top-to-text-medium/desktop, table-header-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-medium-compact/desktop, table-row-checkbox-to-top-medium-spacious/desktop, table-header-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-medium-compact/mobile, table-row-checkbox-to-top-medium-spacious/mobile, table-row-top-to-text-medium-spacious/mobile impacting 5 tokens
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10408947849)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.standard-panel.gripper-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.side-focus-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-bottom-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-checkbox-to-top-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-row-top-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.table-thumbnail-to-top-minimum-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-bottom-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-checkbox-to-top-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-row-top-to-text-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.table-thumbnail-to-top-minimum-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (41) side-focus-indicator, table-row-bottom-to-text-extra-large/desktop, table-row-bottom-to-text-large/desktop, table-row-bottom-to-text-medium/desktop, table-row-bottom-to-text-small/desktop, table-row-checkbox-to-top-extra-large/desktop, table-row-checkbox-to-top-large/desktop, table-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-small/desktop, table-row-height-extra-large/desktop, table-row-height-large/desktop, table-row-height-medium/desktop, table-row-height-small/desktop, table-row-top-to-text-extra-large/desktop, table-row-top-to-text-large/desktop, table-row-top-to-text-medium/desktop, table-row-top-to-text-small/desktop, table-thumbnail-to-top-minimum-extra-large/desktop, table-thumbnail-to-top-minimum-large/desktop, table-thumbnail-to-top-minimum-medium/desktop, table-thumbnail-to-top-minimum-small/desktop, table-row-bottom-to-text-extra-large/mobile, table-row-bottom-to-text-large/mobile, table-row-bottom-to-text-medium/mobile, table-row-bottom-to-text-small/mobile, table-row-checkbox-to-top-extra-large/mobile, table-row-checkbox-to-top-large/mobile, table-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-small/mobile, table-row-height-extra-large/mobile, table-row-height-large/mobile, table-row-height-medium/mobile, table-row-height-small/mobile, table-row-top-to-text-extra-large/mobile, table-row-top-to-text-large/mobile, table-row-top-to-text-medium/mobile, table-row-top-to-text-small/mobile, table-thumbnail-to-top-minimum-extra-large/mobile, table-thumbnail-to-top-minimum-large/mobile, table-thumbnail-to-top-minimum-medium/mobile, table-thumbnail-to-top-minimum-small/mobile
MODIFIED TOKENS: (1) standard-panel-gripper-color-drag
RENAMED TOKENS: (20) table-row-bottom-to-text-extra-large-regular, table-row-bottom-to-text-large-regular, table-row-bottom-to-text-medium-regular, table-row-bottom-to-text-small-regular, table-row-checkbox-to-top-extra-large-regular, table-row-checkbox-to-top-large-regular, table-row-checkbox-to-top-medium-regular, table-row-checkbox-to-top-small-regular, table-row-height-extra-large-regular, table-row-height-large-regular, table-row-height-medium-regular, table-row-height-small-regular, table-row-top-to-text-extra-large-regular, table-row-top-to-text-large-regular, table-row-top-to-text-medium-regular, table-row-top-to-text-small-regular, table-thumbnail-to-top-minimum-extra-large-regular, table-thumbnail-to-top-minimum-large-regular, table-thumbnail-to-top-minimum-medium-regular, table-thumbnail-to-top-minimum-small-regular
DEPRECATED TOKENS: (41) standard-panel-gripper-color-drag/dark, table-row-height-small-regular/desktop, table-row-height-small-regular/mobile, table-row-height-medium-regular/desktop, table-row-height-medium-regular/mobile, table-row-height-large-regular/desktop, table-row-height-large-regular/mobile, table-row-height-extra-large-regular/desktop, table-row-height-extra-large-regular/mobile, table-row-top-to-text-small-regular/desktop, table-row-top-to-text-small-regular/mobile, table-row-top-to-text-medium-regular/desktop, table-row-top-to-text-medium-regular/mobile, table-row-top-to-text-large-regular/desktop, table-row-top-to-text-large-regular/mobile, table-row-top-to-text-extra-large-regular/desktop, table-row-top-to-text-extra-large-regular/mobile, table-row-bottom-to-text-small-regular/desktop, table-row-bottom-to-text-small-regular/mobile, table-row-bottom-to-text-medium-regular/desktop, table-row-bottom-to-text-medium-regular/mobile, table-row-bottom-to-text-large-regular/desktop, table-row-bottom-to-text-large-regular/mobile, table-row-bottom-to-text-extra-large-regular/desktop, table-row-bottom-to-text-extra-large-regular/mobile, table-row-checkbox-to-top-small-regular/desktop, table-row-checkbox-to-top-small-regular/mobile, table-row-checkbox-to-top-medium-regular/desktop, table-row-checkbox-to-top-medium-regular/mobile, table-row-checkbox-to-top-large-regular/desktop, table-row-checkbox-to-top-large-regular/mobile, table-row-checkbox-to-top-extra-large-regular/desktop, table-row-checkbox-to-top-extra-large-regular/mobile, table-thumbnail-to-top-minimum-small-regular/desktop, table-thumbnail-to-top-minimum-small-regular/mobile, table-thumbnail-to-top-minimum-medium-regular/desktop, table-thumbnail-to-top-minimum-medium-regular/mobile, table-thumbnail-to-top-minimum-large-regular/desktop, table-thumbnail-to-top-minimum-large-regular/mobile, table-thumbnail-to-top-minimum-extra-large-regular/desktop, table-thumbnail-to-top-minimum-extra-large-regular/mobile
CHANGED VALUES: (8) table-column-header-row-top-to-text-medium/desktop, table-header-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-medium-compact/desktop, table-row-checkbox-to-top-medium-spacious/desktop, table-header-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-medium-compact/mobile, table-row-checkbox-to-top-medium-spacious/mobile, table-row-top-to-text-medium-spacious/mobile impacting 5 tokens
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
LGTM. Thank you!

**Comment by karstens** [comment]
@GarthDB @PaliwalSparsh @lynnhao @larz0 Is this ready to merge? I didn't follow the conversation. I leave this for you to merge. Thanks.

**Pull request merged**
