### PR TITLE
Added new S2 color token: cinnamon

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description

Added new Spectrum 2 color tokens for both light and dark themes:

- Cinnamon 100 to 1600

## Motivation and context
This is the last new color that is a part of the new color set needed from Premiere Pro. The additional color will also help when creating new data vis color palettes for Spectrum 2.

## Related issue
https://jira.corp.adobe.com/browse/SDS-13197 

## Types of changes

- [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue)
- [X] Minor (add a new token, changing a value; non-breaking change which adds functionality)
- [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.)

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7121850662)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.700
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.800
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.900
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1000
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.700
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.800
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.900
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1000
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1600
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (32) cinnamon-100, cinnamon-200, cinnamon-300, cinnamon-400, cinnamon-500, cinnamon-600, cinnamon-700, cinnamon-800, cinnamon-900, cinnamon-1000, cinnamon-1100, cinnamon-1200, cinnamon-1300, cinnamon-1400, cinnamon-1500, cinnamon-1600, cinnamon-100, cinnamon-200, cinnamon-300, cinnamon-400, cinnamon-500, cinnamon-600, cinnamon-700, cinnamon-800, cinnamon-900, cinnamon-1000, cinnamon-1100, cinnamon-1200, cinnamon-1300, cinnamon-1400, cinnamon-1500, cinnamon-1600
```
</p></details>

TEST COMPLETE

**Review by karstens — COMMENTED** [review]
Looks good to me, I think we wait for another person to review? Please add the perso, who needs to review to this PR @nabuhasan @lynnhao.

**Review by lynnhao — APPROVED** [review]
Reviewed by Lindsay and approved 👍

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7194200417)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.700
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.700
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.800
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.800
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.900
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.900
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1000
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1000
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1100
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1200
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1300
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1400
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1500
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/dark.Palette.cinnamon.1600
UPDATED METADATA - SPECTRUM UUID: spectrum2/palette/light.Palette.cinnamon.1600
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (33) notice-background-color-default/dark, cinnamon-100/dark, cinnamon-100/light, cinnamon-200/dark, cinnamon-200/light, cinnamon-300/dark, cinnamon-300/light, cinnamon-400/dark, cinnamon-400/light, cinnamon-500/dark, cinnamon-500/light, cinnamon-600/dark, cinnamon-600/light, cinnamon-700/dark, cinnamon-700/light, cinnamon-800/dark, cinnamon-800/light, cinnamon-900/dark, cinnamon-900/light, cinnamon-1000/dark, cinnamon-1000/light, cinnamon-1100/dark, cinnamon-1100/light, cinnamon-1200/dark, cinnamon-1200/light, cinnamon-1300/dark, cinnamon-1300/light, cinnamon-1400/dark, cinnamon-1400/light, cinnamon-1500/dark, cinnamon-1500/light, cinnamon-1600/dark, cinnamon-1600/light
MODIFIED TOKENS: (1) notice-background-color-default/light
CHANGED VALUES: (1) notice-background-color-default
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/palette/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/palette/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-palette.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-aliases.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/231)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/22)

**Pull request merged**
