### PR TITLE
Added title-color token

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Added title color token

## Motivation and context

- Title is a new typography style for Spectrum 2, and has a default `title-color` token

## Related issue

- [SDS-13310](https://jira.corp.adobe.com/browse/SDS-13310)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8333496002)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.content.typography.title
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) title-color
```
</p></details>

TEST COMPLETE

**Review by KayiuCarlson — APPROVED** [review]
Looks good!

**Review by mrcjhicks — APPROVED** [review]

**Review by karstens — APPROVED** [review]
Looks good to me.

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8381634875)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.content.typography.title
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) title-color
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-aliases.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/291)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/80)

**Pull request merged**
