### PR TITLE
S2 Rating tokens update

### PR DESCRIPTION
**Pull request by larz0**
Added brand new tokens for S2 Rating:
- rating-width-small
- rating-width-medium
- rating-height-small
- rating-height-medium

- rating-top-to-content-area-small
- rating-top-to-content-area-medium
- rating-bottom-to-content-area-small
- rating-bottom-to-content-area-medium
- rating-edge-to-content-area-small
- rating-edge-to-content-area-medium

Deprecated:
- rating-indicator-width
- rating-indicator-to-icon

## Motivation and context
Added tokens needed for the new S2 standard panel component.

## Related issue

None

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10475996531)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-to-icon: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-width: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-to-icon: ["desktop"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-width: ["desktop"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-medium: ["mobile"]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.standard-panel.gripper-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-top-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-bottom-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-edge-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-top-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-bottom-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-edge-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-height-medium
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (10) rating-top-to-content-area-small/desktop, rating-bottom-to-content-area-small/desktop, rating-edge-to-content-area-small/desktop, rating-top-to-content-area-medium/desktop, rating-bottom-to-content-area-medium/desktop, rating-edge-to-content-area-medium/desktop, rating-width-small/desktop, rating-height-small/desktop, rating-width-medium/desktop, rating-height-medium/desktop
MODIFIED TOKENS: (1) standard-panel-gripper-color-drag
DEPRECATED TOKENS: (3) standard-panel-gripper-color-drag/dark, rating-indicator-width/desktop, rating-indicator-to-icon/desktop
CHANGED VALUES: (48) accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, blue-background-color-default/dark, green-background-color-default/dark, red-background-color-default/dark, brown-background-color-default/dark, cinnamon-background-color-default/dark, cyan-background-color-default/dark, fuchsia-background-color-default/dark, indigo-background-color-default/dark, magenta-background-color-default/dark, pink-background-color-default/dark, purple-background-color-default/dark, seafoam-background-color-default/dark, silver-background-color-default/dark, turquoise-background-color-default/dark, blue-800/dark, green-800/dark, orange-800/dark, red-800/dark, celery-800/dark, chartreuse-800/dark, cyan-800/dark, fuchsia-800/dark, indigo-800/dark, magenta-800/dark, purple-800/dark, seafoam-800/dark, yellow-800/dark, pink-800/dark, turquoise-800/dark, brown-800/dark, cinnamon-800/dark, silver-800/dark impacting 75 tokens
```
</p></details>

TEST COMPLETE

**Comment by karstens** [comment]
> **[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10475996531)**
> 
> READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/` READING tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/` READING tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
> 
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-to-icon: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-width: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-to-icon: ["desktop"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-width: ["desktop"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-small: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-small: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-small: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-medium: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-medium: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-medium: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-small: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-small: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-medium: ["mobile"]
> > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-medium: ["mobile"]
> 
> STUDIO SYNC SUMMARY
> SPECTRUM SYNC SUMMARY
> TEST COMPLETE

Hi @larz0, please have a look at the report. There are a couple of tokens missing... Thanks

**Review by karstens — CHANGES_REQUESTED** [review]
Missing tokens, see report message, please.

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10619041119)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-to-icon: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/🚫 rating-indicator-width: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-to-icon: ["desktop"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-indicator-width: ["desktop"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-top-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-bottom-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-edge-to-content-area-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-width-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/rating-height-medium: ["mobile"]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-top-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-bottom-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-edge-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-top-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-bottom-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-edge-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.rating-height-medium
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (98) neutral-subtle-background-color-default/dark, accent-subtle-background-color-default/dark, informative-subtle-background-color-default/dark, positive-subtle-background-color-default/dark, notice-subtle-background-color-default/dark, negative-subtle-background-color-default/dark, gray-subtle-background-color-default/dark, blue-subtle-background-color-default/dark, green-subtle-background-color-default/dark, orange-subtle-background-color-default/dark, red-subtle-background-color-default/dark, brown-subtle-background-color-default/dark, cinnamon-subtle-background-color-default/dark, celery-subtle-background-color-default/dark, chartreuse-subtle-background-color-default/dark, cyan-subtle-background-color-default/dark, fuchsia-subtle-background-color-default/dark, indigo-subtle-background-color-default/dark, magenta-subtle-background-color-default/dark, pink-subtle-background-color-default/dark, purple-subtle-background-color-default/dark, seafoam-subtle-background-color-default/dark, silver-subtle-background-color-default/dark, turquoise-subtle-background-color-default/dark, yellow-subtle-background-color-default/dark, accent-subtle-background-color-default/light, gray-subtle-background-color-default/light, blue-subtle-background-color-default/light, green-subtle-background-color-default/light, orange-subtle-background-color-default/light, red-subtle-background-color-default/light, brown-subtle-background-color-default/light, cinnamon-subtle-background-color-default/light, celery-subtle-background-color-default/light, chartreuse-subtle-background-color-default/light, cyan-subtle-background-color-default/light, fuchsia-subtle-background-color-default/light, indigo-subtle-background-color-default/light, magenta-subtle-background-color-default/light, pink-subtle-background-color-default/light, purple-subtle-background-color-default/light, seafoam-subtle-background-color-default/light, silver-subtle-background-color-default/light, turquoise-subtle-background-color-default/light, yellow-subtle-background-color-default/light, table-row-bottom-to-text-extra-large/desktop, table-row-bottom-to-text-large/desktop, table-row-bottom-to-text-medium/desktop, table-row-bottom-to-text-small/desktop, table-row-checkbox-to-top-extra-large/desktop, table-row-checkbox-to-top-large/desktop, table-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-small/desktop, table-row-height-extra-large/desktop, table-row-height-large/desktop, table-row-height-medium/desktop, table-row-height-small/desktop, table-row-top-to-text-extra-large/desktop, table-row-top-to-text-large/desktop, table-row-top-to-text-medium/desktop, table-row-top-to-text-small/desktop, table-thumbnail-to-top-minimum-extra-large/desktop, table-thumbnail-to-top-minimum-large/desktop, table-thumbnail-to-top-minimum-medium/desktop, table-thumbnail-to-top-minimum-small/desktop, table-row-bottom-to-text-extra-large/mobile, table-row-bottom-to-text-large/mobile, table-row-bottom-to-text-medium/mobile, table-row-bottom-to-text-small/mobile, table-row-checkbox-to-top-extra-large/mobile, table-row-checkbox-to-top-large/mobile, table-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-small/mobile, table-row-height-extra-large/mobile, table-row-height-large/mobile, table-row-height-medium/mobile, table-row-height-small/mobile, table-row-top-to-text-extra-large/mobile, table-row-top-to-text-large/mobile, table-row-top-to-text-medium/mobile, table-row-top-to-text-small/mobile, table-thumbnail-to-top-minimum-extra-large/mobile, table-thumbnail-to-top-minimum-large/mobile, table-thumbnail-to-top-minimum-medium/mobile, table-thumbnail-to-top-minimum-small/mobile, side-focus-indicator, illustrated-message-horizontal-maximum-width, illustrated-message-vertical-maximum-width, rating-top-to-content-area-small/desktop, rating-bottom-to-content-area-small/desktop, rating-edge-to-content-area-small/desktop, rating-top-to-content-area-medium/desktop, rating-bottom-to-content-area-medium/desktop, rating-edge-to-content-area-medium/desktop, rating-width-small/desktop, rating-height-small/desktop, rating-width-medium/desktop, rating-height-medium/desktop
MODIFIED TOKENS: (6) standard-panel-gripper-color-drag, neutral-subtle-background-color-default/light, informative-subtle-background-color-default/light, positive-subtle-background-color-default/light, notice-subtle-background-color-default/light, negative-subtle-background-color-default/light
RENAMED TOKENS: (20) table-row-bottom-to-text-extra-large-regular, table-row-bottom-to-text-large-regular, table-row-bottom-to-text-medium-regular, table-row-bottom-to-text-small-regular, table-row-checkbox-to-top-extra-large-regular, table-row-checkbox-to-top-large-regular, table-row-checkbox-to-top-medium-regular, table-row-checkbox-to-top-small-regular, table-row-height-extra-large-regular, table-row-height-large-regular, table-row-height-medium-regular, table-row-height-small-regular, table-row-top-to-text-extra-large-regular, table-row-top-to-text-large-regular, table-row-top-to-text-medium-regular, table-row-top-to-text-small-regular, table-thumbnail-to-top-minimum-extra-large-regular, table-thumbnail-to-top-minimum-large-regular, table-thumbnail-to-top-minimum-medium-regular, table-thumbnail-to-top-minimum-small-regular
DEPRECATED TOKENS: (44) standard-panel-gripper-color-drag/dark, rating-indicator-width/desktop, rating-indicator-to-icon/desktop, illustrated-message-maximum-width, table-row-height-small-regular/desktop, table-row-height-small-regular/mobile, table-row-height-medium-regular/desktop, table-row-height-medium-regular/mobile, table-row-height-large-regular/desktop, table-row-height-large-regular/mobile, table-row-height-extra-large-regular/desktop, table-row-height-extra-large-regular/mobile, table-row-top-to-text-small-regular/desktop, table-row-top-to-text-small-regular/mobile, table-row-top-to-text-medium-regular/desktop, table-row-top-to-text-medium-regular/mobile, table-row-top-to-text-large-regular/desktop, table-row-top-to-text-large-regular/mobile, table-row-top-to-text-extra-large-regular/desktop, table-row-top-to-text-extra-large-regular/mobile, table-row-bottom-to-text-small-regular/desktop, table-row-bottom-to-text-small-regular/mobile, table-row-bottom-to-text-medium-regular/desktop, table-row-bottom-to-text-medium-regular/mobile, table-row-bottom-to-text-large-regular/desktop, table-row-bottom-to-text-large-regular/mobile, table-row-bottom-to-text-extra-large-regular/desktop, table-row-bottom-to-text-extra-large-regular/mobile, table-row-checkbox-to-top-small-regular/desktop, table-row-checkbox-to-top-small-regular/mobile, table-row-checkbox-to-top-medium-regular/desktop, table-row-checkbox-to-top-medium-regular/mobile, table-row-checkbox-to-top-large-regular/desktop, table-row-checkbox-to-top-large-regular/mobile, table-row-checkbox-to-top-extra-large-regular/desktop, table-row-checkbox-to-top-extra-large-regular/mobile, table-thumbnail-to-top-minimum-small-regular/desktop, table-thumbnail-to-top-minimum-small-regular/mobile, table-thumbnail-to-top-minimum-medium-regular/desktop, table-thumbnail-to-top-minimum-medium-regular/mobile, table-thumbnail-to-top-minimum-large-regular/desktop, table-thumbnail-to-top-minimum-large-regular/mobile, table-thumbnail-to-top-minimum-extra-large-regular/desktop, table-thumbnail-to-top-minimum-extra-large-regular/mobile
CHANGED VALUES: (65) positive-visual-color/dark, negative-visual-color/dark, accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, blue-background-color-default/dark, green-background-color-default/dark, red-background-color-default/dark, brown-background-color-default/dark, cinnamon-background-color-default/dark, cyan-background-color-default/dark, fuchsia-background-color-default/dark, indigo-background-color-default/dark, magenta-background-color-default/dark, pink-background-color-default/dark, purple-background-color-default/dark, seafoam-background-color-default/dark, silver-background-color-default/dark, turquoise-background-color-default/dark, positive-visual-color/light, notice-visual-color/light, informative-subtle-background-color-default, positive-subtle-background-color-default, notice-subtle-background-color-default, negative-subtle-background-color-default, blue-800/dark, green-800/dark, orange-800/dark, red-800/dark, celery-800/dark, chartreuse-800/dark, cyan-800/dark, fuchsia-800/dark, indigo-800/dark, magenta-800/dark, purple-800/dark, seafoam-800/dark, yellow-800/dark, pink-800/dark, turquoise-800/dark, brown-800/dark, cinnamon-800/dark, silver-800/dark, table-column-header-row-top-to-text-medium/desktop, table-header-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-medium-compact/desktop, table-row-checkbox-to-top-medium-spacious/desktop, table-header-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-medium-compact/mobile, table-row-checkbox-to-top-medium-spacious/mobile, table-row-top-to-text-medium-spacious/mobile, illustrated-message-maximum-width impacting 90 tokens
CHANGED SCHEMAS: (1) illustrated-message-maximum-width
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10620150299)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-top-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-bottom-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-edge-to-content-area-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-top-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-bottom-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-edge-to-content-area-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-height-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.rating-height-medium
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (98) neutral-subtle-background-color-default/dark, accent-subtle-background-color-default/dark, informative-subtle-background-color-default/dark, positive-subtle-background-color-default/dark, notice-subtle-background-color-default/dark, negative-subtle-background-color-default/dark, gray-subtle-background-color-default/dark, blue-subtle-background-color-default/dark, green-subtle-background-color-default/dark, orange-subtle-background-color-default/dark, red-subtle-background-color-default/dark, brown-subtle-background-color-default/dark, cinnamon-subtle-background-color-default/dark, celery-subtle-background-color-default/dark, chartreuse-subtle-background-color-default/dark, cyan-subtle-background-color-default/dark, fuchsia-subtle-background-color-default/dark, indigo-subtle-background-color-default/dark, magenta-subtle-background-color-default/dark, pink-subtle-background-color-default/dark, purple-subtle-background-color-default/dark, seafoam-subtle-background-color-default/dark, silver-subtle-background-color-default/dark, turquoise-subtle-background-color-default/dark, yellow-subtle-background-color-default/dark, accent-subtle-background-color-default/light, gray-subtle-background-color-default/light, blue-subtle-background-color-default/light, green-subtle-background-color-default/light, orange-subtle-background-color-default/light, red-subtle-background-color-default/light, brown-subtle-background-color-default/light, cinnamon-subtle-background-color-default/light, celery-subtle-background-color-default/light, chartreuse-subtle-background-color-default/light, cyan-subtle-background-color-default/light, fuchsia-subtle-background-color-default/light, indigo-subtle-background-color-default/light, magenta-subtle-background-color-default/light, pink-subtle-background-color-default/light, purple-subtle-background-color-default/light, seafoam-subtle-background-color-default/light, silver-subtle-background-color-default/light, turquoise-subtle-background-color-default/light, yellow-subtle-background-color-default/light, table-row-bottom-to-text-extra-large/desktop, table-row-bottom-to-text-large/desktop, table-row-bottom-to-text-medium/desktop, table-row-bottom-to-text-small/desktop, table-row-checkbox-to-top-extra-large/desktop, table-row-checkbox-to-top-large/desktop, table-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-small/desktop, table-row-height-extra-large/desktop, table-row-height-large/desktop, table-row-height-medium/desktop, table-row-height-small/desktop, table-row-top-to-text-extra-large/desktop, table-row-top-to-text-large/desktop, table-row-top-to-text-medium/desktop, table-row-top-to-text-small/desktop, table-thumbnail-to-top-minimum-extra-large/desktop, table-thumbnail-to-top-minimum-large/desktop, table-thumbnail-to-top-minimum-medium/desktop, table-thumbnail-to-top-minimum-small/desktop, table-row-bottom-to-text-extra-large/mobile, table-row-bottom-to-text-large/mobile, table-row-bottom-to-text-medium/mobile, table-row-bottom-to-text-small/mobile, table-row-checkbox-to-top-extra-large/mobile, table-row-checkbox-to-top-large/mobile, table-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-small/mobile, table-row-height-extra-large/mobile, table-row-height-large/mobile, table-row-height-medium/mobile, table-row-height-small/mobile, table-row-top-to-text-extra-large/mobile, table-row-top-to-text-large/mobile, table-row-top-to-text-medium/mobile, table-row-top-to-text-small/mobile, table-thumbnail-to-top-minimum-extra-large/mobile, table-thumbnail-to-top-minimum-large/mobile, table-thumbnail-to-top-minimum-medium/mobile, table-thumbnail-to-top-minimum-small/mobile, side-focus-indicator, illustrated-message-horizontal-maximum-width, illustrated-message-vertical-maximum-width, rating-top-to-content-area-small, rating-bottom-to-content-area-small, rating-edge-to-content-area-small, rating-top-to-content-area-medium, rating-bottom-to-content-area-medium, rating-edge-to-content-area-medium, rating-width-small, rating-height-small, rating-width-medium, rating-height-medium
MODIFIED TOKENS: (6) standard-panel-gripper-color-drag, neutral-subtle-background-color-default/light, informative-subtle-background-color-default/light, positive-subtle-background-color-default/light, notice-subtle-background-color-default/light, negative-subtle-background-color-default/light
RENAMED TOKENS: (20) table-row-bottom-to-text-extra-large-regular, table-row-bottom-to-text-large-regular, table-row-bottom-to-text-medium-regular, table-row-bottom-to-text-small-regular, table-row-checkbox-to-top-extra-large-regular, table-row-checkbox-to-top-large-regular, table-row-checkbox-to-top-medium-regular, table-row-checkbox-to-top-small-regular, table-row-height-extra-large-regular, table-row-height-large-regular, table-row-height-medium-regular, table-row-height-small-regular, table-row-top-to-text-extra-large-regular, table-row-top-to-text-large-regular, table-row-top-to-text-medium-regular, table-row-top-to-text-small-regular, table-thumbnail-to-top-minimum-extra-large-regular, table-thumbnail-to-top-minimum-large-regular, table-thumbnail-to-top-minimum-medium-regular, table-thumbnail-to-top-minimum-small-regular
DEPRECATED TOKENS: (46) standard-panel-gripper-color-drag/dark, rating-indicator-width/desktop, rating-indicator-width/mobile, rating-indicator-to-icon/desktop, rating-indicator-to-icon/mobile, illustrated-message-maximum-width, table-row-height-small-regular/desktop, table-row-height-small-regular/mobile, table-row-height-medium-regular/desktop, table-row-height-medium-regular/mobile, table-row-height-large-regular/desktop, table-row-height-large-regular/mobile, table-row-height-extra-large-regular/desktop, table-row-height-extra-large-regular/mobile, table-row-top-to-text-small-regular/desktop, table-row-top-to-text-small-regular/mobile, table-row-top-to-text-medium-regular/desktop, table-row-top-to-text-medium-regular/mobile, table-row-top-to-text-large-regular/desktop, table-row-top-to-text-large-regular/mobile, table-row-top-to-text-extra-large-regular/desktop, table-row-top-to-text-extra-large-regular/mobile, table-row-bottom-to-text-small-regular/desktop, table-row-bottom-to-text-small-regular/mobile, table-row-bottom-to-text-medium-regular/desktop, table-row-bottom-to-text-medium-regular/mobile, table-row-bottom-to-text-large-regular/desktop, table-row-bottom-to-text-large-regular/mobile, table-row-bottom-to-text-extra-large-regular/desktop, table-row-bottom-to-text-extra-large-regular/mobile, table-row-checkbox-to-top-small-regular/desktop, table-row-checkbox-to-top-small-regular/mobile, table-row-checkbox-to-top-medium-regular/desktop, table-row-checkbox-to-top-medium-regular/mobile, table-row-checkbox-to-top-large-regular/desktop, table-row-checkbox-to-top-large-regular/mobile, table-row-checkbox-to-top-extra-large-regular/desktop, table-row-checkbox-to-top-extra-large-regular/mobile, table-thumbnail-to-top-minimum-small-regular/desktop, table-thumbnail-to-top-minimum-small-regular/mobile, table-thumbnail-to-top-minimum-medium-regular/desktop, table-thumbnail-to-top-minimum-medium-regular/mobile, table-thumbnail-to-top-minimum-large-regular/desktop, table-thumbnail-to-top-minimum-large-regular/mobile, table-thumbnail-to-top-minimum-extra-large-regular/desktop, table-thumbnail-to-top-minimum-extra-large-regular/mobile
CHANGED VALUES: (65) positive-visual-color/dark, negative-visual-color/dark, accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, blue-background-color-default/dark, green-background-color-default/dark, red-background-color-default/dark, brown-background-color-default/dark, cinnamon-background-color-default/dark, cyan-background-color-default/dark, fuchsia-background-color-default/dark, indigo-background-color-default/dark, magenta-background-color-default/dark, pink-background-color-default/dark, purple-background-color-default/dark, seafoam-background-color-default/dark, silver-background-color-default/dark, turquoise-background-color-default/dark, positive-visual-color/light, notice-visual-color/light, informative-subtle-background-color-default, positive-subtle-background-color-default, notice-subtle-background-color-default, negative-subtle-background-color-default, blue-800/dark, green-800/dark, orange-800/dark, red-800/dark, celery-800/dark, chartreuse-800/dark, cyan-800/dark, fuchsia-800/dark, indigo-800/dark, magenta-800/dark, purple-800/dark, seafoam-800/dark, yellow-800/dark, pink-800/dark, turquoise-800/dark, brown-800/dark, cinnamon-800/dark, silver-800/dark, table-column-header-row-top-to-text-medium/desktop, table-header-row-checkbox-to-top-medium/desktop, table-row-checkbox-to-top-medium-compact/desktop, table-row-checkbox-to-top-medium-spacious/desktop, table-header-row-checkbox-to-top-medium/mobile, table-row-checkbox-to-top-medium-compact/mobile, table-row-checkbox-to-top-medium-spacious/mobile, table-row-top-to-text-medium-spacious/mobile, illustrated-message-maximum-width impacting 90 tokens
CHANGED SCHEMAS: (1) illustrated-message-maximum-width
```
</p></details>

TEST COMPLETE

**Comment by larz0** [comment]
@karstens I've added the mobile tokens 👍

**Review by karstens — APPROVED** [review]

**Review by lynnhao — APPROVED** [review]
Looks good!

**Pull request merged**
