### PR TITLE
Deprecated help-text-top-to-workflow-icon-* tokens

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Updated `help-text-top-to-workflow-icon-*` token values to point to `component-top-to-workflow-icon-*` tokens
- Marked `help-text-top-to-workflow-icon-*` tokens for deprecation

## Motivation and context

- Due to design updates for the Spectrum 2 help text component, these `help-text-top-to-workflow-icon-*` component-specific tokens are no longer required since they can use the global aliases instead

## Types of changes

- [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue)
- [x] Minor (add a new token, changing a value; non-breaking change which adds functionality)
- [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.)

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7588028450)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
DEPRECATED TOKENS: (8) help-text-top-to-workflow-icon-small/desktop, help-text-top-to-workflow-icon-small/mobile, help-text-top-to-workflow-icon-medium/desktop, help-text-top-to-workflow-icon-medium/mobile, help-text-top-to-workflow-icon-large/desktop, help-text-top-to-workflow-icon-large/mobile, help-text-top-to-workflow-icon-extra-large/desktop, help-text-top-to-workflow-icon-extra-large/mobile
CHANGED VALUES: (8) help-text-top-to-workflow-icon-extra-large/desktop, help-text-top-to-workflow-icon-large/desktop, help-text-top-to-workflow-icon-medium/desktop, help-text-top-to-workflow-icon-small/desktop, help-text-top-to-workflow-icon-extra-large/mobile, help-text-top-to-workflow-icon-large/mobile, help-text-top-to-workflow-icon-medium/mobile, help-text-top-to-workflow-icon-small/mobile impacting 4 tokens
CHANGED SCHEMAS: (4) help-text-top-to-workflow-icon-extra-large, help-text-top-to-workflow-icon-large, help-text-top-to-workflow-icon-medium, help-text-top-to-workflow-icon-small
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
@GarthDB I wanted to double-check with you on the type of change. Since the tokens have just been marked for deprecation and have not yet been deleted, I believe this is a **minor** change. Could you help confirm if that's correct? Thank you!

**Comment by GarthDB** [comment]
@lynnhao, correct, it's just adding new tokens.

**Review by GarthDB — APPROVED** [review]

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7589403614)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
DEPRECATED TOKENS: (8) help-text-top-to-workflow-icon-small/desktop, help-text-top-to-workflow-icon-small/mobile, help-text-top-to-workflow-icon-medium/desktop, help-text-top-to-workflow-icon-medium/mobile, help-text-top-to-workflow-icon-large/desktop, help-text-top-to-workflow-icon-large/mobile, help-text-top-to-workflow-icon-extra-large/desktop, help-text-top-to-workflow-icon-extra-large/mobile
CHANGED VALUES: (8) help-text-top-to-workflow-icon-extra-large/desktop, help-text-top-to-workflow-icon-large/desktop, help-text-top-to-workflow-icon-medium/desktop, help-text-top-to-workflow-icon-small/desktop, help-text-top-to-workflow-icon-extra-large/mobile, help-text-top-to-workflow-icon-large/mobile, help-text-top-to-workflow-icon-medium/mobile, help-text-top-to-workflow-icon-small/mobile impacting 4 tokens
CHANGED SCHEMAS: (4) help-text-top-to-workflow-icon-extra-large, help-text-top-to-workflow-icon-large, help-text-top-to-workflow-icon-medium, help-text-top-to-workflow-icon-small
```
</p></details>

WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/246)

**Pull request merged**
