### PR TITLE
S2 Popover border token - color only, re-do

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description
**Important: This is second attempt to incorporate popover-border-color token for Popover component. We ran into an issue where in the previously closed PR, $themes.json did not include the latest update. **
 
Reference [closed PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/123) if needed. 

Added net-new tokens:
_Component-specific_

- popover-border-color

This color token was added into both light and dark sets. And variables were created in S2/Variables.

## Motivation and context
These changes occurred as a result of scaling things for S2 design language and experiences.

## Related issue

Reference [closed PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/123) if needed. 
View [Jira task](https://jira.corp.adobe.com/browse/SDS-13389)
View [Popover non-color updates PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/122)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8883637704)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.popover.border
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) popover-border-color
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
oh look, TS added the popover token metadata to the $theme.json 🥳 

..and did some sorting/reordering of some existing tokens, too.  

Thank you for the redo, @nabuhasan!

**Review by lynnhao — APPROVED** [review]
Looks good thank you!

**Comment by karstens** [comment]
@GarthDB This is ready to merge.

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8899957574)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.popover.border
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) popover-border-color
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/component/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/component/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-component.json`

SYNC COMPLETE
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/127)

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/335)

**Pull request merged**
