### PR TITLE
S2 Menu token updates - non-color

### PR DESCRIPTION
**Pull request by nabuhasan**
### Updated existing token:

- menu-item-section-divider-height

### Marked token for deprecation and linked it to new token: 

- 🚫 menu-item-label-to-description --> menu-item-label-to-description-medium

### Added net-new tokens:

**_Component-specific_**
- menu-item-label-to-description-small
- menu-item-label-to-description-medium
- menu-item-label-to-description-large
- menu-item-label-to-description-extra-large
- menu-section-header-to-description-small
- menu-section-header-to-description-medium
- menu-section-header-to-description-large
- menu-section-header-to-description-extra-large
- menu-item-top-to-thumbnail-small
- menu-item-top-to-thumbnail-medium
- menu-item-top-to-thumbnail-large
- menu-item-top-to-thumbnail-extra-large
- menu-item-background-opacity

**_Global_**

- text-to-visual-400
- link-out-icon-size-75
- link-out-icon-size-100
- link-out-icon-size-200

These non-color tokens were added into both desktop and mobile sets.

## Motivation and context
These changes occurred as a result of scaling things for S2 design language and experiences.

## Related issue

View [Jira task](https://jira.corp.adobe.com/browse/SDS-13388)
View [S2 Menu color token updates PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/116)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [X] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8823351480)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/menu-section-header-to-description-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/menu-section-header-to-description-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/menu-section-header-to-description-large: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/menu-section-header-to-description-extra-large: ["mobile"]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/desktop.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/mobile.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-section-header-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-section-header-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-section-header-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-section-header-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-extra-large
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (24) link-out-icon-size-75/desktop, link-out-icon-size-75/mobile, link-out-icon-size-100/desktop, link-out-icon-size-100/mobile, link-out-icon-size-200/desktop, link-out-icon-size-200/mobile, text-to-visual-400/desktop, text-to-visual-400/mobile, menu-item-label-to-description-small, menu-item-label-to-description-medium, menu-item-label-to-description-large, menu-item-label-to-description-extra-large, menu-section-header-to-description-small/desktop, menu-section-header-to-description-medium/desktop, menu-section-header-to-description-large/desktop, menu-section-header-to-description-extra-large/desktop, menu-item-top-to-thumbnail-small/desktop, menu-item-top-to-thumbnail-small/mobile, menu-item-top-to-thumbnail-medium/desktop, menu-item-top-to-thumbnail-medium/mobile, menu-item-top-to-thumbnail-large/desktop, menu-item-top-to-thumbnail-large/mobile, menu-item-top-to-thumbnail-extra-large/desktop, menu-item-top-to-thumbnail-extra-large/mobile
DEPRECATED TOKENS: (1) menu-item-label-to-description
CHANGED VALUES: (2) menu-item-label-to-description, menu-item-section-divider-height
CHANGED SCHEMAS: (1) menu-item-label-to-description
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8823397064)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/desktop.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/mobile.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-extra-large
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (24) link-out-icon-size-75/desktop, link-out-icon-size-75/mobile, link-out-icon-size-100/desktop, link-out-icon-size-100/mobile, link-out-icon-size-200/desktop, link-out-icon-size-200/mobile, text-to-visual-400/desktop, text-to-visual-400/mobile, menu-item-label-to-description-small, menu-item-label-to-description-medium, menu-item-label-to-description-large, menu-item-label-to-description-extra-large, menu-section-header-to-description-small, menu-section-header-to-description-medium, menu-section-header-to-description-large, menu-section-header-to-description-extra-large, menu-item-top-to-thumbnail-small/desktop, menu-item-top-to-thumbnail-small/mobile, menu-item-top-to-thumbnail-medium/desktop, menu-item-top-to-thumbnail-medium/mobile, menu-item-top-to-thumbnail-large/desktop, menu-item-top-to-thumbnail-large/mobile, menu-item-top-to-thumbnail-extra-large/desktop, menu-item-top-to-thumbnail-extra-large/mobile
DEPRECATED TOKENS: (1) menu-item-label-to-description
CHANGED VALUES: (2) menu-item-label-to-description, menu-item-section-divider-height
CHANGED SCHEMAS: (1) menu-item-label-to-description
```
</p></details>

TEST COMPLETE

**Review by karstens — CHANGES_REQUESTED** [review]
I think, the opacity tokens are missing, right?

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8836931579)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/desktop.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/mobile.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.menu-item-background-opacity
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (25) link-out-icon-size-75/desktop, link-out-icon-size-75/mobile, link-out-icon-size-100/desktop, link-out-icon-size-100/mobile, link-out-icon-size-200/desktop, link-out-icon-size-200/mobile, text-to-visual-400/desktop, text-to-visual-400/mobile, menu-item-label-to-description-small, menu-item-label-to-description-medium, menu-item-label-to-description-large, menu-item-label-to-description-extra-large, menu-section-header-to-description-small, menu-section-header-to-description-medium, menu-section-header-to-description-large, menu-section-header-to-description-extra-large, menu-item-top-to-thumbnail-small/desktop, menu-item-top-to-thumbnail-small/mobile, menu-item-top-to-thumbnail-medium/desktop, menu-item-top-to-thumbnail-medium/mobile, menu-item-top-to-thumbnail-large/desktop, menu-item-top-to-thumbnail-large/mobile, menu-item-top-to-thumbnail-extra-large/desktop, menu-item-top-to-thumbnail-extra-large/mobile, menu-item-background-opacity
DEPRECATED TOKENS: (1) menu-item-label-to-description
CHANGED VALUES: (2) menu-item-label-to-description, menu-item-section-divider-height
CHANGED SCHEMAS: (1) menu-item-label-to-description
```
</p></details>

TEST COMPLETE

**Comment by nabuhasan** [comment]
> I think, the opacity tokens are missing, right?

Added, thanks for catching that @karstens

**Review by lynnhao — APPROVED** [review]
Looks good, thank you!

**Review by GarthDB — APPROVED** [review]

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8849935638)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-75
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/desktop.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/icon/mobile.link-out-icon-size-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/desktop.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout/mobile.text-to-visual-400
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-item-label-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.menu-section-header-to-description-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.menu-item-top-to-thumbnail-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.menu-item-background-opacity
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (25) link-out-icon-size-75/desktop, link-out-icon-size-75/mobile, link-out-icon-size-100/desktop, link-out-icon-size-100/mobile, link-out-icon-size-200/desktop, link-out-icon-size-200/mobile, text-to-visual-400/desktop, text-to-visual-400/mobile, menu-item-label-to-description-small, menu-item-label-to-description-medium, menu-item-label-to-description-large, menu-item-label-to-description-extra-large, menu-section-header-to-description-small, menu-section-header-to-description-medium, menu-section-header-to-description-large, menu-section-header-to-description-extra-large, menu-item-top-to-thumbnail-small/desktop, menu-item-top-to-thumbnail-small/mobile, menu-item-top-to-thumbnail-medium/desktop, menu-item-top-to-thumbnail-medium/mobile, menu-item-top-to-thumbnail-large/desktop, menu-item-top-to-thumbnail-large/mobile, menu-item-top-to-thumbnail-extra-large/desktop, menu-item-top-to-thumbnail-extra-large/mobile, menu-item-background-opacity
DEPRECATED TOKENS: (1) menu-item-label-to-description
CHANGED VALUES: (2) menu-item-label-to-description, menu-item-section-divider-height
CHANGED SCHEMAS: (1) menu-item-label-to-description
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/icon/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/icon/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/opacity.component/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/opacity.component/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/121)

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/332)

**Pull request merged**
