### PR TITLE
S2 number field tokens

### PR DESCRIPTION
**Pull request by PaliwalSparsh**
## Description

Made the following changes to component layout tokens for both mobile and desktop.

**New tokens**
number-field-minimum-width-multiplier

number-field-with-stepper-minimum-width-small
number-field-with-stepper-minimum-width-medium
number-field-with-stepper-minimum-width-large
number-field-with-stepper-minimum-width-extra-large

number-field-visual-to-in-field-stepper-small
number-field-visual-to-in-field-stepper-medium
number-field-visual-to-in-field-stepper-large
number-field-visual-to-in-field-stepper-extra-large

in-field-stepper-to-end-small
in-field-stepper-to-end-medium
in-field-stepper-to-end-large
in-field-stepper-to-end-extra-large

## Motivation and context

Added tokens for the S2 number field component.

## Related issue

https://jira.corp.adobe.com/browse/SDS-13938

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11222474171)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.in-field-stepper-to-end-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.in-field-stepper-to-end-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.in-field-stepper-to-end-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.in-field-stepper-to-end-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.in-field-stepper-to-end-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.in-field-stepper-to-end-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.number-field-minimum-width-multiplier
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (23) in-field-stepper-to-end-small/desktop, in-field-stepper-to-end-small/mobile, in-field-stepper-to-end-medium, in-field-stepper-to-end-large, in-field-stepper-to-end-extra-large/desktop, in-field-stepper-to-end-extra-large/mobile, number-field-with-stepper-minimum-width-small/desktop, number-field-with-stepper-minimum-width-small/mobile, number-field-with-stepper-minimum-width-medium/desktop, number-field-with-stepper-minimum-width-medium/mobile, number-field-with-stepper-minimum-width-large/desktop, number-field-with-stepper-minimum-width-large/mobile, number-field-with-stepper-minimum-width-extra-large/desktop, number-field-with-stepper-minimum-width-extra-large/mobile, number-field-visual-to-in-field-stepper-small/desktop, number-field-visual-to-in-field-stepper-small/mobile, number-field-visual-to-in-field-stepper-medium/desktop, number-field-visual-to-in-field-stepper-medium/mobile, number-field-visual-to-in-field-stepper-large/desktop, number-field-visual-to-in-field-stepper-large/mobile, number-field-visual-to-in-field-stepper-extra-large/desktop, number-field-visual-to-in-field-stepper-extra-large/mobile, number-field-minimum-width-multiplier
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11222573943)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.in-field-stepper-to-end-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.in-field-stepper-to-end-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.in-field-stepper-to-end-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.in-field-stepper-to-end-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.in-field-stepper-to-end-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.in-field-stepper-to-end-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-with-stepper-minimum-width-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-with-stepper-minimum-width-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.number-field-visual-to-in-field-stepper-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.number-field-visual-to-in-field-stepper-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.number-field-minimum-width-multiplier
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (23) in-field-stepper-to-end-small/desktop, in-field-stepper-to-end-small/mobile, in-field-stepper-to-end-medium, in-field-stepper-to-end-large, in-field-stepper-to-end-extra-large/desktop, in-field-stepper-to-end-extra-large/mobile, number-field-with-stepper-minimum-width-small/desktop, number-field-with-stepper-minimum-width-small/mobile, number-field-with-stepper-minimum-width-medium/desktop, number-field-with-stepper-minimum-width-medium/mobile, number-field-with-stepper-minimum-width-large/desktop, number-field-with-stepper-minimum-width-large/mobile, number-field-with-stepper-minimum-width-extra-large/desktop, number-field-with-stepper-minimum-width-extra-large/mobile, number-field-visual-to-in-field-stepper-small/desktop, number-field-visual-to-in-field-stepper-small/mobile, number-field-visual-to-in-field-stepper-medium/desktop, number-field-visual-to-in-field-stepper-medium/mobile, number-field-visual-to-in-field-stepper-large/desktop, number-field-visual-to-in-field-stepper-large/mobile, number-field-visual-to-in-field-stepper-extra-large/desktop, number-field-visual-to-in-field-stepper-extra-large/mobile, number-field-minimum-width-multiplier
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]
This PR looks like it's only adding tokens which is expected, so it looks good to me.

**Review by larz0 — APPROVED** [review]
Reviewed and LGTM 👍

**Pull request merged**
