### PR TITLE
Updated values for component pill edge to visual only tokens

### PR DESCRIPTION
**Pull request by KayiuCarlson**
Updated values for component pill edge to visual only tokens for both desktop and mobile.

These values are updated based on the new workflow icon size.

n/a

n/a

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8638315200)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (17) in-field-button-edge-to-fill-small/desktop, in-field-button-edge-to-fill-extra-large/desktop, in-field-progress-circle-edge-to-fill/desktop, in-field-progress-circle-size-75/desktop, in-field-progress-circle-size-100/desktop, in-field-progress-circle-size-200/desktop, in-field-progress-circle-size-300/desktop, in-field-button-edge-to-fill-small/mobile, in-field-button-edge-to-fill-extra-large/mobile, in-field-progress-circle-edge-to-fill/mobile, in-field-progress-circle-size-75/mobile, in-field-progress-circle-size-100/mobile, in-field-progress-circle-size-200/mobile, in-field-progress-circle-size-300/mobile, combo-box-visual-to-field-button, in-field-button-edge-to-fill-medium, in-field-button-edge-to-fill-large
MODIFIED TOKENS: (4) combo-box-visual-to-field-button-extra-large, combo-box-visual-to-field-button-large, combo-box-visual-to-field-button-medium, combo-box-visual-to-field-button-small
DEPRECATED TOKENS: (15) color-loupe-drop-shadow-y, color-loupe-drop-shadow-blur, combo-box-quiet-minimum-width-multiplier, combo-box-visual-to-field-button-small/desktop, combo-box-visual-to-field-button-small/mobile, combo-box-visual-to-field-button-medium/desktop, combo-box-visual-to-field-button-medium/mobile, combo-box-visual-to-field-button-large/desktop, combo-box-visual-to-field-button-large/mobile, combo-box-visual-to-field-button-extra-large/desktop, combo-box-visual-to-field-button-extra-large/mobile, combo-box-visual-to-field-button-quiet, in-field-button-edge-to-fill, drop-shadow-y, drop-shadow-blur
CHANGED VALUES: (14) component-pill-edge-to-visual-only-100/desktop, component-pill-edge-to-visual-only-200/desktop, component-pill-edge-to-visual-only-300/desktop, component-pill-edge-to-visual-only-75/mobile, component-pill-edge-to-visual-only-100/mobile, component-pill-edge-to-visual-only-200/mobile, component-pill-edge-to-visual-only-300/mobile, color-loupe-drop-shadow-blur, color-loupe-drop-shadow-y, combo-box-visual-to-field-button-extra-large/desktop, combo-box-visual-to-field-button-large/desktop, combo-box-visual-to-field-button-medium/desktop, combo-box-visual-to-field-button-quiet, combo-box-visual-to-field-button-small/desktop impacting 11 tokens
CHANGED SCHEMAS: (7) color-loupe-drop-shadow-blur, color-loupe-drop-shadow-y, combo-box-visual-to-field-button-extra-large, combo-box-visual-to-field-button-large, combo-box-visual-to-field-button-medium, combo-box-visual-to-field-button-quiet, combo-box-visual-to-field-button-small
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
looks good to me. thx!

**Review by lynnhao — APPROVED** [review]
thank you!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8727811438)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (7) component-pill-edge-to-visual-only-100/desktop, component-pill-edge-to-visual-only-200/desktop, component-pill-edge-to-visual-only-300/desktop, component-pill-edge-to-visual-only-75/mobile, component-pill-edge-to-visual-only-100/mobile, component-pill-edge-to-visual-only-200/mobile, component-pill-edge-to-visual-only-300/mobile impacting 4 tokens
```
</p></details>

WROTE: `/spectrum-tokens/packages/tokens/src/layout.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/319)

**Pull request merged**
