### PR TITLE
S2 Standard Panel tokens update

### PR DESCRIPTION
**Pull request by larz0**
Added brand new tokens for the S2 Standard Panel:

**Sizing**
- standard-panel-width
- standard-panel-minimum-width
- standard-panel-maximum-width

**Spacing**
- standard-panel-top-to-close-button-compact
- standard-panel-top-to-close-button-regular
- standard-panel-top-to-close-button-spacious
- standard-panel-edge-to-close-button-compact 
- standard-panel-edge-to-close-button regular
- standard-panel-edge-to-close-button-spacious 

**Color**
- standard-panel-gripper-default-color
- standard-panel-gripper-drag-color

**Font size**
- standard-panel-title-font-size

## Motivation and context

Added tokens needed for the new S2 standard panel component.

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10084969799)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.standard-panel.gripper-default
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.standard-panel.gripper-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-maximum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-compact
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-regular
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-spacious
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-compact
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-regular
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-spacious
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.standard-panel-title-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (14) thumbnail-opacity-checkerboard-square-size, thumbnail-corner-radius, standard-panel-gripper-default-color, standard-panel-gripper-drag-color, standard-panel-width, standard-panel-minimum-width, standard-panel-maximum-width, standard-panel-top-to-close-button-compact, standard-panel-top-to-close-button-regular, standard-panel-top-to-close-button-spacious, standard-panel-edge-to-close-button-compact, standard-panel-edge-to-close-button-regular, standard-panel-edge-to-close-button-spacious, standard-panel-title-font-size
CHANGED VALUES: (22) thumbnail-size-75/desktop, thumbnail-size-100/desktop, thumbnail-size-200/desktop, thumbnail-size-300/desktop, thumbnail-size-400/desktop, thumbnail-size-500/desktop, thumbnail-size-600/desktop, thumbnail-size-700/desktop, thumbnail-size-800/desktop, thumbnail-size-900/desktop, thumbnail-size-1000/desktop, thumbnail-size-75/mobile, thumbnail-size-100/mobile, thumbnail-size-200/mobile, thumbnail-size-300/mobile, thumbnail-size-400/mobile, thumbnail-size-500/mobile, thumbnail-size-600/mobile, thumbnail-size-700/mobile, thumbnail-size-800/mobile, thumbnail-size-900/mobile, thumbnail-size-1000/mobile impacting 11 tokens
```
</p></details>

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
This looks fantastic 👏

About the PR, in the "Motivation and context" area – Garth uses the words there directly in his Spectrum Tokens release, so it might be nice to just phrase it in a sentence.

Something like "Added tokens needed for new standard panel component" might work well.

Re: your branch in Figma, I took a look at the variables and everything looks good too. I'll let eng do their approval and I'll merge that in (maybe in time for this week's release 👍)

**Comment by larz0** [comment]
> Something like "Added tokens needed for new standard panel component" might work well.

Updated Motivation and context section 👍

**Review by nabuhasan — APPROVED** [review]
Looks great to me. Congrats on your first tokens PR!

**Review by GarthDB — CHANGES_REQUESTED** [review]
Looking at these 2 tokens:
* `standard-panel-gripper-default-color`
* `standard-panel-gripper-drag-color`

We don't need to include the word `default` and I believe we want the state name to be at the end of the token. So I propose they be changed to:
* `standard-panel-gripper-color`
* `standard-panel-gripper-color-drag`

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10359803031)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/component/Component/standard-panel/gripper-drag: ["light"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/component/Component/standard-panel/gripper-color-drag: ["dark"]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component/dark.Component.standard-panel.gripper
UPDATED METADATA - SPECTRUM UUID: spectrum2/component/light.Component.standard-panel.gripper
UPDATED METADATA - SPECTRUM UUID: spectrum2/component/dark.Component.standard-panel.gripper-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/component/light.Component.standard-panel.gripper-color-drag
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-maximum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-compact
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-regular
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-top-to-close-button-spacious
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-compact
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-regular
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-panel-edge-to-close-button-spacious
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.standard-panel-title-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (14) standard-panel-gripper-default-color/dark, standard-panel-gripper-color/light, standard-panel-gripper-drag-color/dark, standard-panel-gripper-color-drag/light, standard-panel-width, standard-panel-minimum-width, standard-panel-maximum-width, standard-panel-top-to-close-button-compact, standard-panel-top-to-close-button-regular, standard-panel-top-to-close-button-spacious, standard-panel-edge-to-close-button-compact, standard-panel-edge-to-close-button-regular, standard-panel-edge-to-close-button-spacious, standard-panel-title-font-size
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]

**Pull request merged**
