### PR TITLE
S2 tree view tokens

### PR DESCRIPTION
**Pull request by PaliwalSparsh**
## Description

Made the following changes to component layout tokens for both mobile and desktop.

**New tokens**
tree-view-minimum-height
tree-view-minimum-width
tree-view-disclosure-indicator-height
tree-view-disclosure-indicator-width
tree-view-bottom-to-label
tree-view-drag-handle-to-checkbox
tree-view-edge-to-checkbox
tree-view-edge-to-drag-handle
tree-view-end-edge-to-action-area
tree-view-header-to-item
tree-view-item-to-header
tree-view-item-to-item
tree-view-item-to-item-detached
tree-view-label-to-action-area
tree-view-level-increment
tree-view-minimum-top-to-context-area
tree-view-top-to-action-button
tree-view-top-to-checkbox
tree-view-top-to-disclosure-indicator
tree-view-top-to-drag-handle
tree-view-top-to-label

Made the following changes to component opacity tokens for both light and dark.

**New tokens**
tree-view-selected-row-background-opacity-emphasized
tree-view-selected-row-background-opacity-emphasized-hover

Made the following changes to component color tokens for both light and dark.

**New tokens**
tree-view-row-background-hover
tree-view-selected-row-background-default
tree-view-selected-row-background-hover
tree-view-selected-row-background-color-emphasized

## Motivation and context

Made token changes required for the S2 tree view component.

## Related issue

https://jira.corp.adobe.com/browse/SDS-14095

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11605807903)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (2) tree-view-selected-row-background-opacity-emphasized, tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11605841622)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (10) tree-view-disclosure-indicator-height/desktop, tree-view-disclosure-indicator-height/mobile, tree-view-disclosure-indicator-width/desktop, tree-view-disclosure-indicator-width/mobile, tree-view-minimum-height/desktop, tree-view-minimum-height/mobile, tree-view-minimum-width/desktop, tree-view-minimum-width/mobile, tree-view-selected-row-background-opacity-emphasized, tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11605961458)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-bottom-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-bottom-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-drag-handle-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-drag-handle-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-edge-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-edge-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-edge-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-edge-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-end-edge-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-end-edge-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-header-to-item
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-item-to-header
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-item-to-header
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-item-to-item
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-item-to-item-detached
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-label-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-label-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-level-increment
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-level-increment
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-top-to-context-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-top-to-context-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-action-button
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-action-button
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-disclosure-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-disclosure-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (41) tree-view-disclosure-indicator-height/desktop, tree-view-disclosure-indicator-height/mobile, tree-view-disclosure-indicator-width/desktop, tree-view-disclosure-indicator-width/mobile, tree-view-minimum-height/desktop, tree-view-minimum-height/mobile, tree-view-minimum-width/desktop, tree-view-minimum-width/mobile, tree-view-bottom-to-label/desktop, tree-view-bottom-to-label/mobile, tree-view-drag-handle-to-checkbox/desktop, tree-view-drag-handle-to-checkbox/mobile, tree-view-edge-to-checkbox/desktop, tree-view-edge-to-checkbox/mobile, tree-view-edge-to-drag-handle/desktop, tree-view-edge-to-drag-handle/mobile, tree-view-end-edge-to-action-area/desktop, tree-view-end-edge-to-action-area/mobile, tree-view-header-to-item, tree-view-item-to-header/desktop, tree-view-item-to-header/mobile, tree-view-item-to-item, tree-view-item-to-item-detached, tree-view-label-to-action-area/desktop, tree-view-label-to-action-area/mobile, tree-view-level-increment/desktop, tree-view-level-increment/mobile, tree-view-minimum-top-to-context-area/desktop, tree-view-minimum-top-to-context-area/mobile, tree-view-top-to-action-button/desktop, tree-view-top-to-action-button/mobile, tree-view-top-to-checkbox/desktop, tree-view-top-to-checkbox/mobile, tree-view-top-to-disclosure-indicator/desktop, tree-view-top-to-disclosure-indicator/mobile, tree-view-top-to-drag-handle/desktop, tree-view-top-to-drag-handle/mobile, tree-view-top-to-label/desktop, tree-view-top-to-label/mobile, tree-view-selected-row-background-opacity-emphasized, tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/11606120838)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.tree-view.row-background-hover
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.tree-view.selected-row-background-color-emphasized
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.tree-view.selected-row-background-default
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.tree-view.selected-row-background-hover
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-disclosure-indicator-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-bottom-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-bottom-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-drag-handle-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-drag-handle-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-edge-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-edge-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-edge-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-edge-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-end-edge-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-end-edge-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-header-to-item
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-item-to-header
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-item-to-header
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-item-to-item
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.tree-view-item-to-item-detached
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-label-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-label-to-action-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-level-increment
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-level-increment
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-minimum-top-to-context-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-minimum-top-to-context-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-action-button
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-action-button
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-checkbox
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-disclosure-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-disclosure-indicator
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-drag-handle
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.tree-view-top-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.tree-view-top-to-label
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (45) tree-view-row-background-hover, tree-view-selected-row-background-color-emphasized, tree-view-selected-row-background-default, tree-view-selected-row-background-hover, tree-view-disclosure-indicator-height/desktop, tree-view-disclosure-indicator-height/mobile, tree-view-disclosure-indicator-width/desktop, tree-view-disclosure-indicator-width/mobile, tree-view-minimum-height/desktop, tree-view-minimum-height/mobile, tree-view-minimum-width/desktop, tree-view-minimum-width/mobile, tree-view-bottom-to-label/desktop, tree-view-bottom-to-label/mobile, tree-view-drag-handle-to-checkbox/desktop, tree-view-drag-handle-to-checkbox/mobile, tree-view-edge-to-checkbox/desktop, tree-view-edge-to-checkbox/mobile, tree-view-edge-to-drag-handle/desktop, tree-view-edge-to-drag-handle/mobile, tree-view-end-edge-to-action-area/desktop, tree-view-end-edge-to-action-area/mobile, tree-view-header-to-item, tree-view-item-to-header/desktop, tree-view-item-to-header/mobile, tree-view-item-to-item, tree-view-item-to-item-detached, tree-view-label-to-action-area/desktop, tree-view-label-to-action-area/mobile, tree-view-level-increment/desktop, tree-view-level-increment/mobile, tree-view-minimum-top-to-context-area/desktop, tree-view-minimum-top-to-context-area/mobile, tree-view-top-to-action-button/desktop, tree-view-top-to-action-button/mobile, tree-view-top-to-checkbox/desktop, tree-view-top-to-checkbox/mobile, tree-view-top-to-disclosure-indicator/desktop, tree-view-top-to-disclosure-indicator/mobile, tree-view-top-to-drag-handle/desktop, tree-view-top-to-drag-handle/mobile, tree-view-top-to-label/desktop, tree-view-top-to-label/mobile, tree-view-selected-row-background-opacity-emphasized, tree-view-selected-row-background-opacity-emphasized-hover
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]

**Pull request merged**
