### PR TITLE
Added dragged drop shadow tokens

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Added `dragged` drop shadow tokens that point to new `300` global drop shadow tokens
- This update includes x, y, and blur values as well as new color tokens and variables
- This also fixes the token type of the non-color drop-shadow sizing tokens

## Motivation and context

- These are new foundational drop shadow tokens that represent a higher elevation when items are dragged. The more prominent shadow also brings more visual focus to the dragged item. They will be used in the standard panel "dragged" state, as well as in future component updates, to be determined.

## Related issue

[SDS-13543](https://jira.corp.adobe.com/browse/SDS-13543)
[DTT-2043](https://jira.corp.adobe.com/browse/DTT-2043)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10011674405)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.drop-shadow.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.drop-shadow.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.drop-shadow.dragged
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-blur
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (11) thumbnail-opacity-checkerboard-square-size, thumbnail-corner-radius, drop-shadow-color-300/dark, drop-shadow-color-300/light, drop-shadow-dragged-color, drop-shadow-x-300, drop-shadow-y-300, drop-shadow-blur-300, drop-shadow-dragged-x, drop-shadow-dragged-y, drop-shadow-dragged-blur
CHANGED VALUES: (22) thumbnail-size-75/desktop, thumbnail-size-100/desktop, thumbnail-size-200/desktop, thumbnail-size-300/desktop, thumbnail-size-400/desktop, thumbnail-size-500/desktop, thumbnail-size-600/desktop, thumbnail-size-700/desktop, thumbnail-size-800/desktop, thumbnail-size-900/desktop, thumbnail-size-1000/desktop, thumbnail-size-75/mobile, thumbnail-size-100/mobile, thumbnail-size-200/mobile, thumbnail-size-300/mobile, thumbnail-size-400/mobile, thumbnail-size-500/mobile, thumbnail-size-600/mobile, thumbnail-size-700/mobile, thumbnail-size-800/mobile, thumbnail-size-900/mobile, thumbnail-size-1000/mobile impacting 11 tokens
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
looks good to me! 🎈

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10012469741)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.drop-shadow.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.drop-shadow.300
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.drop-shadow.dragged
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-300
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-dragged-blur
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (11) thumbnail-opacity-checkerboard-square-size, thumbnail-corner-radius, drop-shadow-color-300/dark, drop-shadow-color-300/light, drop-shadow-dragged-color, drop-shadow-x-300, drop-shadow-y-300, drop-shadow-blur-300, drop-shadow-dragged-x, drop-shadow-dragged-y, drop-shadow-dragged-blur
CHANGED VALUES: (22) thumbnail-size-75/desktop, thumbnail-size-100/desktop, thumbnail-size-200/desktop, thumbnail-size-300/desktop, thumbnail-size-400/desktop, thumbnail-size-500/desktop, thumbnail-size-600/desktop, thumbnail-size-700/desktop, thumbnail-size-800/desktop, thumbnail-size-900/desktop, thumbnail-size-1000/desktop, thumbnail-size-75/mobile, thumbnail-size-100/mobile, thumbnail-size-200/mobile, thumbnail-size-300/mobile, thumbnail-size-400/mobile, thumbnail-size-500/mobile, thumbnail-size-600/mobile, thumbnail-size-700/mobile, thumbnail-size-800/mobile, thumbnail-size-900/mobile, thumbnail-size-1000/mobile impacting 11 tokens
```
</p></details>

TEST COMPLETE

**Review by nabuhasan — APPROVED** [review]
No concerns, looks good!

**Pull request merged**
