### PR TITLE
Added new Standard dialog tokens

### PR DESCRIPTION
**Pull request by KayiuCarlson**
Added new Standard dialog tokens.

Six new Standard dialog specific tokens: 

- standard-dialog-maximum-width-small
- standard-dialog-maximum-width-medium
- standard-dialog-maximum-width-large
- standard-dialog-minimum-width
- standard-dialog-title-font-size
- standard-dialog-body-font-size

n/a

n/a

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8667915251)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/standard-dialog-maximum-width-small: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/standard-dialog-minimum-width: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/standard-dialog-maximum-width-medium: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum2/layout.component/standard-dialog-maximum-width-large: ["mobile"]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-maximum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-maximum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-maximum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (8) standard-dialog-maximum-width-small/desktop, standard-dialog-minimum-width/desktop, standard-dialog-maximum-width-medium/desktop, standard-dialog-maximum-width-large/desktop, standard-dialog-title-font-size/desktop, standard-dialog-title-font-size/mobile, standard-dialog-body-font-size/desktop, standard-dialog-body-font-size/mobile
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
@KayiuCarlson the values for these tokens also need to be added to the mobile set, even if the value is the same:
* `standard-dialog-maximum-width-small`
* `standard-dialog-maximum-width-medium`
* `standard-dialog-maximum-width-large`
* `standard-dialog-minimum-width`

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8692644124)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (8) standard-dialog-maximum-width-small, standard-dialog-minimum-width, standard-dialog-maximum-width-medium, standard-dialog-maximum-width-large, standard-dialog-title-font-size/desktop, standard-dialog-title-font-size/mobile, standard-dialog-body-font-size/desktop, standard-dialog-body-font-size/mobile
```
</p></details>

TEST COMPLETE

**Comment by KayiuCarlson** [comment]
@lynnhao oh, that makes sense! I just added the values for the min and max widths to the mobile set!

**Review by karstens — APPROVED** [review]

**Review by lynnhao — APPROVED** [review]
Thank you Kayiu, it looks good!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8728143818)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-minimum-width
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.standard-dialog-maximum-width-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.standard-dialog-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.standard-dialog-body-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (8) standard-dialog-maximum-width-small, standard-dialog-minimum-width, standard-dialog-maximum-width-medium, standard-dialog-maximum-width-large, standard-dialog-title-font-size/desktop, standard-dialog-title-font-size/mobile, standard-dialog-body-font-size/desktop, standard-dialog-body-font-size/mobile
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/321)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/110)

**Pull request merged**
