### PR TITLE
Updated background aliases in dark theme; added new non-semantic colors

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

Updated colors in dark theme only for: 
- `neutral-subdued-background-color-*`
- Semantic background colors, including: `accent-background-color-*`, `informative-background-color-*`, `positive-background-color-*`, `negative-background-color-*`, `notice-background-color-default`
- Non-semantic background colors, including: `gray-background-color-default`, `orange-background-color-default`,  `yellow-background-color-default`, `chartreuse-background-color-default`, `celery-background-color-default`

Added new non-semantic colors:
- `pink-visual-color`, `turquoise-visual-color`, `brown-visual-color`, `cinnamon-visual-color`, `silver-visual-color`
- `pink-background-color-default`, `turquoise-background-color-default`, `brown-background-color-default`, `cinnamon-background-color-default`, `silver-background-color-default`

## Motivation and context

- The existing background colors were updated for better consistency across semantic and non-semantic variants of the Badge component. The colors also introduce some general improved contrast in dark theme across other components using these aliases.
- The new non-semantic visual and background colors were added because new hues were introduced. These colors will be used in status light and badge components, respectively.

## Related issue

[SDS-13308](https://jira.corp.adobe.com/browse/SDS-13308)
[SDS-13309](https://jira.corp.adobe.com/browse/SDS-13309)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8087879126)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.gray
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) gray-background-color-default/dark
MODIFIED TOKENS: (1) gray-background-color-default/light
CHANGED VALUES: (25) neutral-subdued-background-color-default/dark, neutral-subdued-background-color-hover/dark, neutral-subdued-background-color-down/dark, neutral-subdued-background-color-key-focus/dark, accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, notice-background-color-default/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, orange-background-color-default/dark, celery-background-color-default/dark, chartreuse-background-color-default/dark, yellow-background-color-default/dark impacting 26 tokens
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8088080912)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.gray
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.turquoise
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (21) gray-background-color-default/dark, brown-visual-color/dark, brown-visual-color/light, cinnamon-visual-color/dark, cinnamon-visual-color/light, pink-visual-color/dark, pink-visual-color/light, silver-visual-color/dark, silver-visual-color/light, turquoise-visual-color/dark, turquoise-visual-color/light, brown-background-color-default/dark, brown-background-color-default/light, cinnamon-background-color-default/dark, cinnamon-background-color-default/light, pink-background-color-default/dark, pink-background-color-default/light, silver-background-color-default/dark, silver-background-color-default/light, turquoise-background-color-default/dark, turquoise-background-color-default/light
MODIFIED TOKENS: (1) gray-background-color-default/light
CHANGED VALUES: (25) neutral-subdued-background-color-default/dark, neutral-subdued-background-color-hover/dark, neutral-subdued-background-color-down/dark, neutral-subdued-background-color-key-focus/dark, accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, notice-background-color-default/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, orange-background-color-default/dark, celery-background-color-default/dark, chartreuse-background-color-default/dark, yellow-background-color-default/dark impacting 26 tokens
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]
These are a lot of changes, if the values are correct, I'm good with this.

**Review by nabuhasan — APPROVED** [review]
After eyes looking back and forth between Git and Figma, everything looks great!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8102522340)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.gray
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.content.visual.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.content.visual.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.brown
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.cinnamon
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.pink
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.silver
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.non-semantic.turquoise
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.background.non-semantic.turquoise
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (21) gray-background-color-default/dark, brown-visual-color/dark, brown-visual-color/light, cinnamon-visual-color/dark, cinnamon-visual-color/light, pink-visual-color/dark, pink-visual-color/light, silver-visual-color/dark, silver-visual-color/light, turquoise-visual-color/dark, turquoise-visual-color/light, brown-background-color-default/dark, brown-background-color-default/light, cinnamon-background-color-default/dark, cinnamon-background-color-default/light, pink-background-color-default/dark, pink-background-color-default/light, silver-background-color-default/dark, silver-background-color-default/light, turquoise-background-color-default/dark, turquoise-background-color-default/light
MODIFIED TOKENS: (1) gray-background-color-default/light
CHANGED VALUES: (25) neutral-subdued-background-color-default/dark, neutral-subdued-background-color-hover/dark, neutral-subdued-background-color-down/dark, neutral-subdued-background-color-key-focus/dark, accent-background-color-default/dark, accent-background-color-hover/dark, accent-background-color-down/dark, accent-background-color-key-focus/dark, informative-background-color-default/dark, informative-background-color-hover/dark, informative-background-color-down/dark, informative-background-color-key-focus/dark, positive-background-color-default/dark, positive-background-color-hover/dark, positive-background-color-down/dark, positive-background-color-key-focus/dark, notice-background-color-default/dark, negative-background-color-default/dark, negative-background-color-hover/dark, negative-background-color-down/dark, negative-background-color-key-focus/dark, orange-background-color-default/dark, celery-background-color-default/dark, chartreuse-background-color-default/dark, yellow-background-color-default/dark impacting 26 tokens
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-aliases.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/269)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/66)

**Pull request merged**
