### PR TITLE
fix: alpha-numeric sorting of tokens

### PR DESCRIPTION
**Pull request by karstens**
## Description

* get tokens with number in the token name sorted/ordered properly by alpha-numeric order
* spectrum-non-color data only

## Related issue

https://jira.corp.adobe.com/browse/DTT-1952

## Types of changes

- [X] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue)
- [ ] Minor (add a new token, changing a value; non-breaking change which adds functionality)
- [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.)

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7532496045)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

TEST COMPLETE

**Comment by karstens** [comment]
example: 
Screenshot 2024-01-15 at 19 03 02

**Review by nabuhasan — APPROVED** [review]
This looks great to me, thanks for making these updates!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7555451538)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY


SYNC COMPLETE

**Pull request merged**
