### PR TITLE
Updated Component/color-loupe/drop-shadow name on Figma

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Updated Figma name from `Component/color-loupe/🚫drop-shadow` to `Component/color-loupe/🚫 drop-shadow`

## Motivation and context

- This is consistent with other deprecations in the colors

## Types of changes

<li> [x] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8840172765)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

TEST COMPLETE

**Comment by lynnhao** [comment]
Note: I added a space for consistency, but we can also remove all spaces if that's better, in a future release.

**Review by karstens — APPROVED** [review]
Looks good to me. Thank you!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8881243092)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY


SYNC COMPLETE

**Pull request merged**
