### PR TITLE
Color slider border rounding value update

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description
Updated `color-slider-border-rounding` token to use 7px instead of 4px in desktop only.
This token value update is the same value used by alias token: corner-radius-medium-size-small. 

## Motivation and context

S2 color slider design updates. 

## Related issue

This update is a part of this [Jira ticket](https://jira.corp.adobe.com/browse/SDS-13302) body of work. And relates to this [PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/60). 

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8012698664)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.color-slider-border-rounding
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) color-slider-border-rounding/mobile
MODIFIED TOKENS: (1) color-slider-border-rounding/desktop
CHANGED VALUES: (1) color-slider-border-rounding
```
</p></details>

TEST COMPLETE

**Review by mrcjhicks — APPROVED** [review]

**Comment by lynnhao** [comment]
I think @nabuhasan, we had discussed that the value should just be `corner-radius-medium-size-small` so that if that token is updated in the future, this component would also update. Wanted to check in case something changed since we last discussed in the Figma spec!

**Comment by nabuhasan** [comment]
@lynnhao I tried linking that alias and it did not work for me. It may have been because the alias is in a different set layout vs layout.component. I was only able to see corner-radius-1000.

**Comment by karstens** [comment]
@nabuhasan Did you look into the layout desktop set? 

Screenshot 2024-02-23 at 10 21 51

**Comment by lynnhao** [comment]
Thanks @karstens! 

@nabuhasan – You can modify the "type" in the JSON to `borderRadius`, which will allow the corner radius tokens to show up. Here's some screenshots on what to update in your branch in case that helps.

Screenshot 2024-02-23 at 8 55 33 AM
Screenshot 2024-02-23 at 8 56 14 AM

**Review by lynnhao — APPROVED** [review]
Thank you, looks great!

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8071512857)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

  > WARNING - studio token uuid collision: (991541a2-df44-4f32-90a5-de698adf5db3)
  >           spectrum2/layout.component/desktop,color-slider-border-rounding
  >           spectrum2/layout.component/mobile,color-slider-border-rounding


TEST COMPLETE

**Pull request merged**
