### PR TITLE
S2 Popover tokens update, non-color

### PR DESCRIPTION
**Pull request by nabuhasan**
### Marked token for deprecation and linked it to new token:

- 🚫 popover-top-to-content-area --> popover-edge-to-content-area

### Added net-new tokens:
**Component-specific**

- popover-border-opacity

## Motivation and context
These changes occurred as a result of scaling things for S2 design language and experiences.

## Related issue
View [Jira task](https://jira.corp.adobe.com/browse/SDS-13389)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8854223544)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 popover-top-to-content-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.popover-edge-to-content-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component/dark.popover-border-opacity
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component/light.popover-border-opacity
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (3) popover-edge-to-content-area, popover-border-opacity/dark, popover-border-opacity/light
MODIFIED TOKENS: (1) popover-top-to-content-area
DEPRECATED TOKENS: (4) overlay-opacity/light, overlay-opacity/dark, popover-top-to-content-area/desktop, popover-top-to-content-area/mobile
CHANGED VALUES: (1) popover-top-to-content-area/desktop
CHANGED SCHEMAS: (1) popover-top-to-content-area
```
</p></details>

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
Looks great!

**Review by karstens — APPROVED** [review]

**Comment by GarthDB** [comment]
It looks like an opacity is being added on a non-color pr, is that ok @karstens @nabuhasan ?

**Comment by karstens** [comment]
> It looks like an opacity is being added on a non-color pr, is that ok @karstens @nabuhasan ?

@GarthDB yes, opacity tokens are all in the "non-color" data, at the moment.

**Comment by karstens** [comment]
@GarthDB This is ready to merge.

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8899925416)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 popover-top-to-content-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.popover-edge-to-content-area
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component/dark.popover-border-opacity
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component/light.popover-border-opacity
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (3) popover-edge-to-content-area, popover-border-opacity/dark, popover-border-opacity/light
MODIFIED TOKENS: (1) popover-top-to-content-area
DEPRECATED TOKENS: (4) overlay-opacity/light, overlay-opacity/dark, popover-top-to-content-area/desktop, popover-top-to-content-area/mobile
CHANGED VALUES: (1) popover-top-to-content-area/desktop
CHANGED SCHEMAS: (1) popover-top-to-content-area
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/opacity.component/dark.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/opacity.component/light.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`
WROTE: `/spectrum-tokens/packages/tokens/src/color-aliases.json`

SYNC COMPLETE
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/126)

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/334)

**Pull request merged**
