### PR TITLE
S2 toast and color area non-color token updates

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description
Updated the following **toast** token values, in desktop and mobile scales:

- toast-height
- toast-top-to-workflow-icon
- toast-top-to-text
- toast-bottom-to-text

Updated the following **color area** token type from _spacing_ to _borderRadius_ and adjusted value referenced, desktop and mobile scale:

- color-area-border-rounding

More information captured in toast [Jira ticket](https://jira.corp.adobe.com/browse/SDS-13311) and color area [Jira ticket](https://jira.corp.adobe.com/browse/SDS-13312).

## Motivation and context

These changes occurred as a result of scaling things for S2 design language and experiences.

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [X] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8163995634)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (9) toast-bottom-to-text/desktop, toast-height/desktop, toast-top-to-text/desktop, toast-top-to-workflow-icon/desktop, toast-bottom-to-text/mobile, toast-height/mobile, toast-top-to-text/mobile, toast-top-to-workflow-icon/mobile, color-area-border-rounding impacting 5 tokens
```
</p></details>

TEST COMPLETE

**Review by mrcjhicks — APPROVED** [review]

**Review by karstens — APPROVED** [review]
Looks good to me. 👍

**Review by lynnhao — APPROVED** [review]
Looks good, thank you!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8190626341)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (8) field-width-small/desktop, field-width-medium/desktop, field-width-large/desktop, field-width-extra-large/desktop, field-width-small/mobile, field-width-medium/mobile, field-width-large/mobile, field-width-extra-large/mobile
MODIFIED TOKENS: (4) side-label-character-count-top-margin-extra-large, side-label-character-count-top-margin-large, side-label-character-count-top-margin-medium, side-label-character-count-top-margin-small
RENAMED TOKENS: (1) field-width
DEPRECATED TOKENS: (26) field-label-to-component-quiet-small/desktop, field-label-to-component-quiet-small/mobile, field-label-to-component-quiet-medium/desktop, field-label-to-component-quiet-medium/mobile, field-label-to-component-quiet-large/desktop, field-label-to-component-quiet-large/mobile, field-label-to-component-quiet-extra-large/desktop, field-label-to-component-quiet-extra-large/mobile, field-edge-to-text-quiet, field-edge-to-border-quiet, field-edge-to-alert-icon-quiet, field-edge-to-validation-icon-quiet, field-width/desktop, field-width/mobile, character-count-to-field-quiet-small/desktop, character-count-to-field-quiet-small/mobile, character-count-to-field-quiet-medium/desktop, character-count-to-field-quiet-medium/mobile, character-count-to-field-quiet-large/desktop, character-count-to-field-quiet-large/mobile, character-count-to-field-quiet-extra-large/desktop, character-count-to-field-quiet-extra-large/mobile, side-label-character-count-top-margin-small/mobile, side-label-character-count-top-margin-medium/mobile, side-label-character-count-top-margin-large/mobile, side-label-character-count-top-margin-extra-large/mobile
CHANGED VALUES: (18) alert-banner-bottom-to-text/desktop, alert-banner-minimum-height/desktop, alert-banner-top-to-text/desktop, alert-banner-top-to-workflow-icon/desktop, toast-bottom-to-text/desktop, toast-height/desktop, toast-top-to-text/desktop, toast-top-to-workflow-icon/desktop, toast-bottom-to-text/mobile, toast-height/mobile, toast-top-to-text/mobile, toast-top-to-workflow-icon/mobile, side-label-character-count-top-margin-extra-large/desktop, side-label-character-count-top-margin-large/desktop, side-label-character-count-top-margin-medium/desktop, side-label-character-count-top-margin-small/desktop, color-area-border-rounding, search-field-minimum-width-multiplier impacting 14 tokens
```
</p></details>

WROTE: `/spectrum-tokens/packages/tokens/src/layout.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/278)

**Pull request merged**
