### PR TITLE
fix: icon token for foundation

### PR DESCRIPTION
**Pull request by karstens**
## Motivation and context

Screenshot 2024-06-21 at 17 59 32

Screenshot 2024-06-21 at 17 59 45

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Review by lynnhao — CHANGES_REQUESTED** [review]
Thank you so much for making these updates @karstens! 

All the values entered look correct, but I do see `component-pill-edge-to-visual-only` missing. Those values should be slightly updated for S2 in order to keep the same height/width on icon-only variants.

**Comment by karstens** [comment]
@lynnhao Thank you for reviewing. Yes, I will double-check the `component-pill-edge-to-visual-only-*` tokens. They were not listed in the paper doc as "changed values", so I missed them. I will edit the dropbox paper and update this PR.

**Comment by karstens** [comment]
@lynnhao Update: okay, I double-checked the values for `component-pill-edge-to-visual-only-*` in desktop/mobile with what I found in the tokens specs (see screenshot). Hope this is correct, now. 

Screenshot 2024-06-24 at 16 29 24

**Comment by lynnhao** [comment]
@karstens Thank you so much! The values you've attached are correct, but I'm still not seeing the `mobile` values entered. I might be missing something though.

**Comment by karstens** [comment]
> @karstens Thank you so much! The values you've attached are correct, but I'm still not seeing the `mobile` values entered. I might be missing something though.

Oh no, my mistake. Please check, now. I have fixed the `mobile` values. ✅

**Review by lynnhao — APPROVED** [review]
Thank you so much @karstens, this looks great!

**Pull request merged**
