### PR TITLE
Fixing misnamed accordion token

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

Jason Chan found a token misnamed. It is named `accordion-small-top-to-text-spacious` when it should be `accordion-top-to-text-spacious-small`. This pr fixes it.

## Motivation and context

Make the token names consistent.

## Types of changes

<li> [x] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8427707118)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum/layout.component/desktop.accordion-top-to-text-spacious-small
UPDATED METADATA - SPECTRUM UUID: spectrum/layout.component/mobile.accordion-top-to-text-spacious-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (2) accordion-top-to-text-spacious-small/desktop, accordion-top-to-text-spacious-small/mobile
DEPRECATED TOKENS: (2) accordion-small-top-to-text-spacious/desktop, accordion-small-top-to-text-spacious/mobile
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8427707117)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.accordion-top-to-text-spacious-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.accordion-top-to-text-spacious-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (2) accordion-top-to-text-spacious-small/desktop, accordion-top-to-text-spacious-small/mobile
DEPRECATED TOKENS: (2) accordion-small-top-to-text-spacious/desktop, accordion-small-top-to-text-spacious/mobile
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
Thank you @GarthDB for fixing this! I noticed it was marked as deprecated and then a new one was added. Curious why you did this instead of updating the name?

**Comment by GarthDB** [comment]
@lynnhao its a breaking change to just change the name of the token. Anytime we change the name of a token, especially one that's been around awhile, we should deprecate the old name and add the new name as a new token. It gives products some time to update the token without it breaking their code immediately.

**Comment by lynnhao** [comment]
> @lynnhao its a breaking change to just change the name of the token. Anytime we change the name of a token, especially one that's been around awhile, we should deprecate the old name and add the new name as a new token. It gives products some time to update the token without it breaking their code immediately.

Got it, thank you! I will add this our deprecation notes so that we do this moving forward.

**Review by lynnhao — APPROVED** [review]

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8428116029)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum/layout.component/desktop.accordion-top-to-text-spacious-small
UPDATED METADATA - SPECTRUM UUID: spectrum/layout.component/mobile.accordion-top-to-text-spacious-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (2) accordion-top-to-text-spacious-small/desktop, accordion-top-to-text-spacious-small/mobile
DEPRECATED TOKENS: (2) accordion-small-top-to-text-spacious/desktop, accordion-small-top-to-text-spacious/mobile
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/spectrum/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/spectrum/layout.component/mobile.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/292)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/82)

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8428116025)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.accordion-top-to-text-spacious-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.accordion-top-to-text-spacious-small
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (2) accordion-top-to-text-spacious-small/desktop, accordion-top-to-text-spacious-small/mobile
DEPRECATED TOKENS: (2) accordion-small-top-to-text-spacious/desktop, accordion-small-top-to-text-spacious/mobile
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/293)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/83)

**Pull request merged**
