### PR TITLE
Adding Title typography tokens

### PR DESCRIPTION
**Pull request by KayiuCarlson**
Adding new Title typography tokens.

Adding new Title typography tokens in font family, font weight, font style, font size, line height, and margins. 

n/a

n/a

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8195491034)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-bottom-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-top-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-weight
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (45) title-cjk-emphasized-font-style, title-cjk-emphasized-font-weight, title-cjk-font-family, title-cjk-font-style, title-cjk-font-weight, title-cjk-strong-emphasized-font-style, title-cjk-strong-emphasized-font-weight, title-cjk-strong-font-style, title-cjk-strong-font-weight, title-sans-serif-emphasized-font-style, title-sans-serif-emphasized-font-weight, title-sans-serif-font-family, title-sans-serif-font-style, title-sans-serif-strong-emphasized-font-style, title-sans-serif-strong-emphasized-font-weight, title-sans-serif-strong-font-style, title-sans-serif-strong-font-weight, title-serif-emphasized-font-style, title-serif-emphasized-font-weight, title-serif-font-family, title-serif-font-style, title-serif-strong-emphasized-font-style, title-serif-strong-emphasized-font-weight, title-serif-strong-font-style, title-serif-strong-font-weight, title-size-l, title-size-m, title-size-s, title-size-xl, title-size-xs, title-size-xxl, title-size-xxxl, title-cjk-line-height, title-cjk-size-l, title-cjk-size-m, title-cjk-size-s, title-cjk-size-xl, title-cjk-size-xs, title-cjk-size-xxl, title-cjk-size-xxxl, title-line-height, title-margin-bottom-multiplier, title-margin-top-multiplier, title-sans-serif-font-weight, title-serif-font-weight
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8200572104)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-bottom-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-top-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-weight
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (45) title-cjk-emphasized-font-style, title-cjk-emphasized-font-weight, title-cjk-font-family, title-cjk-font-style, title-cjk-font-weight, title-cjk-strong-emphasized-font-style, title-cjk-strong-emphasized-font-weight, title-cjk-strong-font-style, title-cjk-strong-font-weight, title-sans-serif-emphasized-font-style, title-sans-serif-emphasized-font-weight, title-sans-serif-font-family, title-sans-serif-font-style, title-sans-serif-strong-emphasized-font-style, title-sans-serif-strong-emphasized-font-weight, title-sans-serif-strong-font-style, title-sans-serif-strong-font-weight, title-serif-emphasized-font-style, title-serif-emphasized-font-weight, title-serif-font-family, title-serif-font-style, title-serif-strong-emphasized-font-style, title-serif-strong-emphasized-font-weight, title-serif-strong-font-style, title-serif-strong-font-weight, title-size-l, title-size-m, title-size-s, title-size-xl, title-size-xs, title-size-xxl, title-size-xxxl, title-cjk-line-height, title-cjk-size-l, title-cjk-size-m, title-cjk-size-s, title-cjk-size-xl, title-cjk-size-xs, title-cjk-size-xxl, title-cjk-size-xxxl, title-line-height, title-margin-bottom-multiplier, title-margin-top-multiplier, title-sans-serif-font-weight, title-serif-font-weight
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
I merged the latest changes from 'main' branch into this. Now, only the typography changes are in this PR.

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8270277047)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-bottom-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-top-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxxl
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (45) title-cjk-emphasized-font-style, title-cjk-emphasized-font-weight, title-cjk-font-family, title-cjk-font-style, title-cjk-font-weight, title-cjk-line-height, title-cjk-size-l, title-cjk-size-m, title-cjk-size-s, title-cjk-size-xl, title-cjk-size-xs, title-cjk-size-xxl, title-cjk-size-xxxl, title-cjk-strong-emphasized-font-style, title-cjk-strong-emphasized-font-weight, title-cjk-strong-font-style, title-cjk-strong-font-weight, title-line-height, title-margin-bottom-multiplier, title-margin-top-multiplier, title-sans-serif-emphasized-font-style, title-sans-serif-emphasized-font-weight, title-sans-serif-font-family, title-sans-serif-font-style, title-sans-serif-font-weight, title-sans-serif-strong-emphasized-font-style, title-sans-serif-strong-emphasized-font-weight, title-sans-serif-strong-font-style, title-sans-serif-strong-font-weight, title-serif-emphasized-font-style, title-serif-emphasized-font-weight, title-serif-font-family, title-serif-font-style, title-serif-font-weight, title-serif-strong-emphasized-font-style, title-serif-strong-emphasized-font-weight, title-serif-strong-font-style, title-serif-strong-font-weight, title-size-l, title-size-m, title-size-s, title-size-xl, title-size-xs, title-size-xxl, title-size-xxxl
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8270300396)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-size-xxxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-cjk-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-line-height
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-bottom-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-margin-top-multiplier
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-sans-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-family
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-emphasized-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-style
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-serif-strong-font-weight
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-l
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-m
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-s
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xs
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxl
UPDATED METADATA - SPECTRUM UUID: spectrum2/typography.component.title-size-xxxl
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (45) title-cjk-emphasized-font-style, title-cjk-emphasized-font-weight, title-cjk-font-family, title-cjk-font-style, title-cjk-font-weight, title-cjk-line-height, title-cjk-size-l, title-cjk-size-m, title-cjk-size-s, title-cjk-size-xl, title-cjk-size-xs, title-cjk-size-xxl, title-cjk-size-xxxl, title-cjk-strong-emphasized-font-style, title-cjk-strong-emphasized-font-weight, title-cjk-strong-font-style, title-cjk-strong-font-weight, title-line-height, title-margin-bottom-multiplier, title-margin-top-multiplier, title-sans-serif-emphasized-font-style, title-sans-serif-emphasized-font-weight, title-sans-serif-font-family, title-sans-serif-font-style, title-sans-serif-font-weight, title-sans-serif-strong-emphasized-font-style, title-sans-serif-strong-emphasized-font-weight, title-sans-serif-strong-font-style, title-sans-serif-strong-font-weight, title-serif-emphasized-font-style, title-serif-emphasized-font-weight, title-serif-font-family, title-serif-font-style, title-serif-font-weight, title-serif-strong-emphasized-font-style, title-serif-strong-emphasized-font-weight, title-serif-strong-font-style, title-serif-strong-font-weight, title-size-l, title-size-m, title-size-s, title-size-xl, title-size-xs, title-size-xxl, title-size-xxxl
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/typography.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/typography.component/mobile.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/285)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/74)

**Pull request merged**
