### PR TITLE
S2 Alert banner and search field token updates

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description

Update the following **alert banner** token values, desktop only scale:

- alert-banner-minimum-height
- alert-banner-top-to-workflow-icon
- alert-banner-top-to-text from
- alert-banner-bottom-to-text

Updated the following **search field** token value, desktop and mobile scale: 

- search-field-minimum-width-multiplier

More information captured in alert banner [Jira ticket](https://jira.corp.adobe.com/browse/SDS-13275) and search field [Jira ticket](https://jira.corp.adobe.com/browse/SDS-13307). 

## Motivation and context
These changes occurred as a result of scaling things for S2 design language and experiences. 

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8103363542)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (5) alert-banner-bottom-to-text/desktop, alert-banner-minimum-height/desktop, alert-banner-top-to-text/desktop, alert-banner-top-to-workflow-icon/desktop, search-field-minimum-width-multiplier
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]

**Review by lynnhao — APPROVED** [review]
Checked the values, looks great!

**Review by karstens — APPROVED** [review]
Looks good to me. 👍

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8176535245)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (5) alert-banner-bottom-to-text/desktop, alert-banner-minimum-height/desktop, alert-banner-top-to-text/desktop, alert-banner-top-to-workflow-icon/desktop, search-field-minimum-width-multiplier
```
</p></details>

WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/271)

**Pull request merged**
