### PR TITLE
Updated S2 Swatch and introduced S2 Swatch-group tokens

### PR DESCRIPTION
**Pull request by nabuhasan**
## Description

Updated S2 swatch tokens and added swatch-group tokens in S2 Color and S2 Non-color data sets, respectively. 

**_Color_**

- swatch-border-color
- swatch-group-border-color

**_Non-color_**

- swatch-border-opacity
- swatch-disabled-icon-border-opacity
- swatch-group-spacious-spacing
- swatch-group-border-opacity

## Motivation and context

Swatch and swatch group components are being formalized as Spectrum 2 components. These tokens define the design data needed for implementation. Changes include updated corner rounding, colors and spacing for spacious density. 

For more information, [view Jira ticket](https://jira.corp.adobe.com/browse/SDS-13497).

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9861610659)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.swatch-group.border
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) swatch-group-border-color
CHANGED VALUES: (1) swatch-border-color
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9862136187)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.swatch-group.border
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.swatch-group-spacing-spacious
UPDATED METADATA - SPECTRUM UUID: spectrum2/opacity.component.swatch-group-border-opacity
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (5) thumbnail-opacity-checkerboard-square-size, thumbnail-corner-radius, swatch-group-border-color, swatch-group-spacing-spacious, swatch-group-border-opacity
CHANGED VALUES: (25) thumbnail-size-75/desktop, thumbnail-size-100/desktop, thumbnail-size-200/desktop, thumbnail-size-300/desktop, thumbnail-size-400/desktop, thumbnail-size-500/desktop, thumbnail-size-600/desktop, thumbnail-size-700/desktop, thumbnail-size-800/desktop, thumbnail-size-900/desktop, thumbnail-size-1000/desktop, thumbnail-size-75/mobile, thumbnail-size-100/mobile, thumbnail-size-200/mobile, thumbnail-size-300/mobile, thumbnail-size-400/mobile, thumbnail-size-500/mobile, thumbnail-size-600/mobile, thumbnail-size-700/mobile, thumbnail-size-800/mobile, thumbnail-size-900/mobile, thumbnail-size-1000/mobile, swatch-border-color, swatch-border-opacity, swatch-disabled-icon-border-opacity impacting 14 tokens
```
</p></details>

TEST COMPLETE

**Review by karstens — APPROVED** [review]
Looks good to me! 👍

**Review by lynnhao — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
