### PR TITLE
Updated contextual help tokens for S2

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Fixed token type from `Sizing` to `Font size` for `contextual-help-body-size` and `contextual-help-title-size`
- Renamed tokens by deprecating previous ones and creating new ones, with `font` in the token name
- Updated value of `contextual-help-title-font-size`

## Motivation and context

- The updated type sorts them correctly in the Tokens Studio data
- The updated value reflects the latest design for Spectrum 2, using the new title style instead of heading

## Related issue

[SDS-13416](https://jira.corp.adobe.com/browse/SDS-13416)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [ ] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [x] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9374694532)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (2) contextual-help-title-size/desktop, contextual-help-title-size/mobile impacting 1 tokens
```
</p></details>

TEST COMPLETE

**Comment by karstens** [comment]
Hi @lynnhao, I would like to know, if these token names should have the word "font", like the change we did for these tokens here: https://github.com/adobe/spectrum-tokens-studio-data/pull/124/files
I have this as the last open item of https://jira.corp.adobe.com/browse/DTT-2054.

**Review by nabuhasan — APPROVED** [review]
No concerns, looks good!

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9390400671)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 contextual-help-body-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 contextual-help-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.contextual-help-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.contextual-help-body-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.contextual-help-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.contextual-help-title-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (4) contextual-help-body-font-size/desktop, contextual-help-body-font-size/mobile, contextual-help-title-font-size/desktop, contextual-help-title-font-size/mobile
MODIFIED TOKENS: (2) contextual-help-body-size, contextual-help-title-size
DEPRECATED TOKENS: (4) contextual-help-title-size/desktop, contextual-help-title-size/mobile, contextual-help-body-size/desktop, contextual-help-body-size/mobile
CHANGED VALUES: (2) contextual-help-body-size/desktop, contextual-help-title-size/desktop
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
> Hi @lynnhao, I would like to know, if these token names should have the word "font", like the change we did for these tokens here: https://github.com/adobe/spectrum-tokens-studio-data/pull/124/files I have this as the last open item of https://jira.corp.adobe.com/browse/DTT-2054.

Thank you for remembering this, I've updated the tokens to include `font` in the name by deprecating the previous ones and creating new tokens!

**Review by karstens — APPROVED** [review]
Looks good to me. Thanks 🫶

**Pull request merged**
