### PR TITLE
fix: missing overlay-opacity token

### PR DESCRIPTION
**Pull request by karstens**
## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9615595022)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/dark [31d5b502-6266-4309-8f8a-3892e6e158da]
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: overlay-opacity/light [26b9803c-577f-4a29-badd-dfc459e8b73e]


<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (4) contextual-help-body-font-size/desktop, contextual-help-title-font-size/desktop, contextual-help-body-font-size/mobile, contextual-help-title-font-size/mobile
MODIFIED TOKENS: (2) contextual-help-body-size, contextual-help-title-size
DEPRECATED TOKENS: (6) contextual-help-title-size/desktop, contextual-help-title-size/mobile, contextual-help-body-size/desktop, contextual-help-body-size/mobile, contextual-help-body-size, contextual-help-title-size
CHANGED VALUES: (2) contextual-help-body-size/desktop, contextual-help-title-size/desktop
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/9615595024)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
Thank you so much, this looks good!

**Review by nabuhasan — APPROVED** [review]

**Comment by karstens** [comment]
@GarthDB @mrcjhicks Please review and approve. Thanks

**Pull request merged**
