### PR TITLE
updated component-top-to-workflow and text-to-visual padding

### PR DESCRIPTION
**Pull request by KayiuCarlson**
## Description

Updated component-top-to-workflow and text-to-visual padding.

## Motivation and context

Updated padding values due to new workflow icon sizes in S2.

## Related issue

N/A

## Types of changes

- [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue)
- [x] Minor (add a new token, changing a value; non-breaking change which adds functionality)
- [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.)

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7465481010)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
CHANGED VALUES: (18) component-top-to-workflow-icon-100/desktop, component-top-to-workflow-icon-200/desktop, component-top-to-workflow-icon-300/desktop, text-to-visual-100/desktop, text-to-visual-200/desktop, text-to-visual-300/desktop, text-to-visual-50/desktop, text-to-visual-75/desktop, component-top-to-workflow-icon-100/mobile, component-top-to-workflow-icon-200/mobile, component-top-to-workflow-icon-300/mobile, component-top-to-workflow-icon-50/mobile, component-top-to-workflow-icon-75/mobile, text-to-visual-100/mobile, text-to-visual-200/mobile, text-to-visual-300/mobile, text-to-visual-50/mobile, text-to-visual-75/mobile impacting 10 tokens
```
</p></details>

TEST COMPLETE

**Review by GarthDB — APPROVED** [review]

**Review by lynnhao — APPROVED** [review]
Looks great!

**Review by karstens — APPROVED** [review]
Looks good to me, thank you @KayiuCarlson!

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7479630402)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (6) component-size-difference-down/desktop, component-size-width-ratio-down/desktop, component-size-minimum-perspective-down/desktop, component-size-difference-down/mobile, component-size-width-ratio-down/mobile, component-size-minimum-perspective-down/mobile
CHANGED VALUES: (26) workflow-icon-size-100/desktop, workflow-icon-size-200/desktop, workflow-icon-size-300/desktop, workflow-icon-size-100/mobile, workflow-icon-size-200/mobile, workflow-icon-size-300/mobile, workflow-icon-size-50/mobile, workflow-icon-size-75/mobile, component-top-to-workflow-icon-100/desktop, component-top-to-workflow-icon-200/desktop, component-top-to-workflow-icon-300/desktop, text-to-visual-100/desktop, text-to-visual-200/desktop, text-to-visual-300/desktop, text-to-visual-50/desktop, text-to-visual-75/desktop, component-top-to-workflow-icon-100/mobile, component-top-to-workflow-icon-200/mobile, component-top-to-workflow-icon-300/mobile, component-top-to-workflow-icon-50/mobile, component-top-to-workflow-icon-75/mobile, text-to-visual-100/mobile, text-to-visual-200/mobile, text-to-visual-300/mobile, text-to-visual-50/mobile, text-to-visual-75/mobile impacting 15 tokens
```
</p></details>

WROTE: `/spectrum-tokens/packages/tokens/src/layout.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/239)

**Pull request merged**
