### PR TITLE
Fixed bug in notice-background-color-default

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

Fixed bug in the light theme value for `notice-background-color-default`, from `notice-color-800` to `notice-color-600`

## Motivation and context

While updating the badge component in Figma, we noticed a bug where `notice-background-color-default` in S2 was entered incorrectly for light theme, and should instead match the value for S1

## Related issue

N/A – no Jira ticket for this patch

## Types of changes

- [X] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue)
- [ ] Minor (add a new token, changing a value; non-breaking change which adds functionality)
- [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.)

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7134112258)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - studio token uuid collision: (48f3445a-63d8-4477-a2f5-1fee6a022328)
  >           spectrum2/alias/dark,Alias,background,semantic,notice,default
  >           spectrum2/alias/light,Alias,background,semantic,notice,default
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


TEST COMPLETE

**Review by GarthDB — APPROVED** [review]

**Comment by mrcjhicks** [comment]
> WARNING - studio token uuid collision: (48f3445a-63d8-4477-a2f5-1fee6a022328)
> spectrum2/alias/dark,Alias,background,semantic,notice,default
> spectrum2/alias/light,Alias,background,semantic,notice,default

This warning is triggering because these two tokens have their _constant-token-duplicate_ value set to true (their values are expected to be identical), but with this change their values are no longer the same so they need to be unique token entries in spectrum-tokens.

I'm not sure what we do with uuids in this situation, @GarthDB. Do we deprecate the existing token definition with the current uuid, and create new ones for the separate light/dark values? Or something else?

**Comment by karstens** [comment]
@GarthDB @mrcjhicks I think, we talked about using the uuid for light and generate new uuids for the other themes, in case this happens. [slack disc.](https://adobedesign.slack.com/archives/C039GTY1PKP/p1695649420746529). 
I would expect the test script to:
* warn the other about the uuid collision (which it does nicely here, thanks @mrcjhicks), 
* update/generate the uuid for the dark token
* update the constant-token-duplicate to false
After merge, the sync script would apply the changes to spectrum-tokens and split up the constant token there as well. 
(note: have I mentioned, that I advocate to eliminate the constant tokens in spectrum-tokens completely? ;-))

**Review by nabuhasan — APPROVED** [review]

**Comment by mrcjhicks** [comment]
@karstens Thanks for the clarification; I'll make the changes to the diff script to resolve this type of an issue using the workflow you described.

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7134112258)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - studio token uuid collision: (48f3445a-63d8-4477-a2f5-1fee6a022328)
  >           spectrum2/alias/dark,Alias,background,semantic,notice,default
  >           spectrum2/alias/light,Alias,background,semantic,notice,default
  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7146418958)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.semantic.notice.default
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) notice-background-color-default/dark
MODIFIED TOKENS: (1) notice-background-color-default/light
CHANGED VALUES: (1) notice-background-color-default
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7146431716)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

  > WARNING - STUDIO INCLUDES DEPRECATED TOKEN: floating-action-button-shadow-color [f843b1b7-4b2f-496e-a679-b0372e49d575]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.background.semantic.notice.default
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) notice-background-color-default/dark
MODIFIED TOKENS: (1) notice-background-color-default/light
CHANGED VALUES: (1) notice-background-color-default
```
</p></details>
WROTE: /home/runner/work/spectrum-tokens-studio-data/spectrum-tokens-studio-data/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/dark.json
WROTE: /home/runner/work/spectrum-tokens-studio-data/spectrum-tokens-studio-data/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/spectrum2/alias/light.json
WROTE: /home/runner/work/spectrum-tokens-studio-data/spectrum-tokens-studio-data/spectrum-tokens/packages/tokens/src/color-aliases.json

SYNC COMPLETE
\n[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/230)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/19)

**Pull request merged**
