### PR TITLE
Updated values and added new tokens for Switch

### PR DESCRIPTION
**Pull request by KayiuCarlson**
Updated values and added new tokens for Switch.

Added new tokens: `switch-handle-size-*` and `switch-handle-selected-size-*` for both desktop and mobile.
Update token values on: `switch-control-width-*` and `switch-control-height-*` for both desktop and mobile.

The design for Switch in S2 has changed and now has a border when it's not selected. New handle sizes are added and control sizes have been updated. 

N/A

N/A

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [ ] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7836749110)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-extra-large
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (16) switch-handle-size-small/desktop, switch-handle-size-small/mobile, switch-handle-selected-size-small/desktop, switch-handle-selected-size-small/mobile, switch-handle-selected-size-medium/desktop, switch-handle-selected-size-medium/mobile, switch-handle-selected-size-large/desktop, switch-handle-selected-size-large/mobile, switch-handle-selected-size-extra-large/desktop, switch-handle-selected-size-extra-large/mobile, switch-handle-size-medium/desktop, switch-handle-size-medium/mobile, switch-handle-size-large/desktop, switch-handle-size-large/mobile, switch-handle-size-extra-large/desktop, switch-handle-size-extra-large/mobile
CHANGED VALUES: (14) switch-control-height-extra-large/desktop, switch-control-height-large/desktop, switch-control-height-medium/desktop, switch-control-height-small/desktop, switch-control-width-extra-large/desktop, switch-control-width-large/desktop, switch-control-width-small/desktop, switch-control-height-extra-large/mobile, switch-control-height-large/mobile, switch-control-height-medium/mobile, switch-control-height-small/mobile, switch-control-width-large/mobile, switch-control-width-medium/mobile, switch-control-width-small/mobile impacting 8 tokens
```
</p></details>

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
Double-checked the values and everything looks good, thank you!

**Review by mrcjhicks — APPROVED** [review]

**Review by karstens — APPROVED** [review]
LGTM. Thank you!

**Comment by karstens** [comment]
@GarthDB  Is this okay to merge? Or are there pending PRs on the spectrum-tokens repo to be merged first?

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/7888316001)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-small
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-selected-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-selected-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-medium
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.switch-handle-size-extra-large
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.switch-handle-size-extra-large
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (16) switch-handle-size-small/desktop, switch-handle-size-small/mobile, switch-handle-selected-size-small/desktop, switch-handle-selected-size-small/mobile, switch-handle-selected-size-medium/desktop, switch-handle-selected-size-medium/mobile, switch-handle-selected-size-large/desktop, switch-handle-selected-size-large/mobile, switch-handle-selected-size-extra-large/desktop, switch-handle-selected-size-extra-large/mobile, switch-handle-size-medium/desktop, switch-handle-size-medium/mobile, switch-handle-size-large/desktop, switch-handle-size-large/mobile, switch-handle-size-extra-large/desktop, switch-handle-size-extra-large/mobile
CHANGED VALUES: (14) switch-control-height-extra-large/desktop, switch-control-height-large/desktop, switch-control-height-medium/desktop, switch-control-height-small/desktop, switch-control-width-extra-large/desktop, switch-control-width-large/desktop, switch-control-width-small/desktop, switch-control-height-extra-large/mobile, switch-control-height-large/mobile, switch-control-height-medium/mobile, switch-control-height-small/mobile, switch-control-width-large/mobile, switch-control-width-medium/mobile, switch-control-width-small/mobile impacting 8 tokens
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/desktop.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout.component/mobile.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout-component.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/260)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/55)

**Pull request merged**
