### PR TITLE
S2 Popover token updates - color only

### PR DESCRIPTION
**Pull request by nabuhasan**
### Added net-new tokens:

**Component-specific**
- popover-border-color

This color token was added into both light and dark sets. And variables were created in S2/Variables.

## Motivation and context

These changes occurred as a result of scaling things for S2 design language and experiences.
## Related issue
View [Jira task](https://jira.corp.adobe.com/browse/SDS-13389)
View [Popover non-color updates PR](https://github.com/adobe/spectrum-tokens-studio-data/pull/122)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [X] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [X] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8854386411)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.popover.border
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) popover-border-color
```
</p></details>

TEST COMPLETE

**Review by lynnhao — APPROVED** [review]
Looks great!

**Review by karstens — CHANGES_REQUESTED** [review]
This is a new token in the color set. This set is synced with the figma variables collection. So, this PR should also show a new token in the $theme.json, unless you haven't synced the tokens studio data with Figma? 
Otherwise we will get the changes in another PR. That lead to confusion the other day 
cc @nabuhasan @lynnhao

**Comment by nabuhasan** [comment]
> This is a new token in the color set. This set is synced with the figma variables collection. So, this PR should also show a new token in the $theme.json, unless you haven't synced the tokens studio data with Figma? Otherwise we will get the changes in another PR. That lead to confusion the other day cc @nabuhasan @lynnhao
Screenshot 2024-04-29 at 8 43 56 AM

@karstens @lynnhao I did sync TS with S2/Variables and I see the popover border color present for both themes. I also updated this information in both light and dark sets in TS JSON. Am I missing something?

**Comment by karstens** [comment]
> > This is a new token in the color set. This set is synced with the figma variables collection. So, this PR should also show a new token in the $theme.json, unless you haven't synced the tokens studio data with Figma? Otherwise we will get the changes in another PR. That lead to confusion the other day cc @nabuhasan @lynnhao
> 
> Screenshot 2024-04-29 at 8 43 56 AM
> @karstens @lynnhao I did sync TS with S2/Variables and I see the popover border color present for both themes. I also updated this information in both light and dark sets in TS JSON. Am I missing something?

yes, there is something missing in this PR. In the $themes.json, there should be the mapping from the tokens studio token name to the figma variable ID. Did you run "create styles" or "sync styles"? I am not sure, why this is happing, I just know, that it is either a bug or something else... 
See screenshot?
Screenshot 2024-04-29 at 18 00 16

**Comment by karstens** [comment]
@nabuhasan did you create this PR before or after syncing the variables with Figma?

**Comment by nabuhasan** [comment]
> > > This is a new token in the color set. This set is synced with the figma variables collection. So, this PR should also show a new token in the $theme.json, unless you haven't synced the tokens studio data with Figma? Otherwise we will get the changes in another PR. That lead to confusion the other day cc @nabuhasan @lynnhao
> > 
> > 
> > Screenshot 2024-04-29 at 8 43 56 AM
> > @karstens @lynnhao I did sync TS with S2/Variables and I see the popover border color present for both themes. I also updated this information in both light and dark sets in TS JSON. Am I missing something?
> 
> yes, there is something missing in this PR. In the $themes.json, there should be the mapping from the tokens studio token name to the figma variable ID. Did you run "create styles" or "sync styles"? I am not sure, why this is happing, I just know, that it is either a bug or something else... See screenshot? Screenshot 2024-04-29 at 18 00 16

@karstens I didn't create or sync styles, instead I selected "Create variables", that's the action I take when there are new color variables we need to add and is also what [we documented as our process](https://www.figma.com/file/eHjfEN4Mi7pWBW0JpBYWKO/Tokens-process-brainstorm?type=design&node-id=594-2096&mode=design&t=j1NrbhZuUHE7UXK3-4).

**Comment by karstens** [comment]
> > > > This is a new token in the color set. This set is synced with the figma variables collection. So, this PR should also show a new token in the $theme.json, unless you haven't synced the tokens studio data with Figma? Otherwise we will get the changes in another PR. That lead to confusion the other day cc @nabuhasan @lynnhao
> > > 
> > > 
> > > Screenshot 2024-04-29 at 8 43 56 AM
> > > @karstens @lynnhao I did sync TS with S2/Variables and I see the popover border color present for both themes. I also updated this information in both light and dark sets in TS JSON. Am I missing something?
> > 
> > 
> > yes, there is something missing in this PR. In the $themes.json, there should be the mapping from the tokens studio token name to the figma variable ID. Did you run "create styles" or "sync styles"? I am not sure, why this is happing, I just know, that it is either a bug or something else... See screenshot? Screenshot 2024-04-29 at 18 00 16
> 
> @karstens I didn't create or sync styles, instead I selected "Create variables", that's the action I take when there are new color variables we need to add and is also what [we documented as our process](https://www.figma.com/file/eHjfEN4Mi7pWBW0JpBYWKO/Tokens-process-brainstorm?type=design&node-id=594-2096&mode=design&t=j1NrbhZuUHE7UXK3-4).
> 
> Also, I always pull updates in main then create a branch off of main, create or update what is required, then create variables (specifically for color tokens). My understanding is that once these are incorporated, then Cable runs a script to create styles (for any new additions) based on the latest changes in S2/Variables. Would it help to re-do this again and we delete this?

@nabuhasan Sorry, I meant "create variables" vs "sync styles". You are right and all that you describe sounds correct. The documented process, as well as the actions you list, as well as Cable's script to ”create the styles". 
Did you create/sync the changes of *this* pr into a branch of the figma variables library? I think, if we don't merge this git branch, and so tokens of this PR are in a branch of the S2/Variables, that hasn't been merged yet, we could delete this and try again.

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8883270707)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/component.Component.popover.border
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (1) popover-border-color
```
</p></details>

TEST COMPLETE

**Comment by nabuhasan** [comment]
Closing pull request to ensure the $themes.json includes the popover border color for light and dark. Will try including updates in a new PR.

**Pull request closed without merging**
