### PR TITLE
Updated S1 tokens - typography, foundations

### PR DESCRIPTION
**Pull request by larz0**
## Description

Added:
- font-size-25
- letter-spacing

Updated
- cjk-letter-spacing

## Motivation and context
Added and updated S1 typography, foundations tokens.

## Related issue
[SDS-13795](https://jira.corp.adobe.com/browse/SDS-13795)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value, deprecating a token; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type, renaming a token by deprecating the old one; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10517323104)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`

  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum/typography/letter-spacing: ["mobile"]
  > WARNING - STUDIO MISSING MODE DEFINITION FOR spectrum/typography/font-size-25: ["mobile"]


<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/desktop.cjk-letter-spacing
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/mobile.cjk-letter-spacing
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/desktop.letter-spacing
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/desktop.font-size-25
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (4) cjk-letter-spacing/desktop, cjk-letter-spacing/mobile, letter-spacing/desktop, font-size-25/desktop
DEPRECATED TOKENS: (1) cjk-letter-spacing
```
</p></details>

TEST COMPLETE

**Comment by karstens** [comment]
@larz0 please have a look at the report. you made some token changes in the desktop set, but not in the mobile set?! See https://github.com/adobe/spectrum-tokens-studio-data/pull/177#issuecomment-2305928401

**Review by karstens — CHANGES_REQUESTED** [review]
please fix the mobile entries. thx.

**Comment by mrcjhicks** [comment]
**[TESTING spectrum](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/10568891863)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-colors/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum-non-colors/`

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum/typography.letter-spacing
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/desktop.font-size-25
UPDATED METADATA - SPECTRUM UUID: spectrum/typography/mobile.font-size-25
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (3) letter-spacing, font-size-25/desktop, font-size-25/mobile
CHANGED VALUES: (1) cjk-letter-spacing
CHANGED SCHEMAS: (1) cjk-letter-spacing
```
</p></details>

TEST COMPLETE

**Comment by larz0** [comment]
@karstens I've added and updated tokens for mobile. Thank you 🙏

**Comment by karstens** [comment]
Hi @larz0, this looks good! I am just not sure, if I understand the 'foundations'. If this is for foundation tokens, you would need to add it to the foundation data. See https://github.com/adobe/spectrum-tokens-studio-data/pull/180.
Please reach out to @GarthDB.

**Comment by GarthDB** [comment]
We clarified, foundations does not mean S2 Foundations, so this is unrelated to #180

**Review by GarthDB — APPROVED** [review]

**Comment by karstens** [comment]
Got it. S2 Foundations != Typography Foundations. Sorry for being behind...

**Review by karstens — APPROVED** [review]

**Review by lynnhao — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
