### PR TITLE
Updated and added S2 drop shadow tokens

### PR DESCRIPTION
**Pull request by lynnhao**
## Description

- Renamed previous drop shadow tokens from S1 and pointed them to the new `100` S2 drop shadow tokens
- Added new drop shadow tokens, `100`, `200`, `emphasized-default`, `emphasized-hover`, `elevated`

## Motivation and context

- These tokens reflect the updates to drop tokens foundations in Spectrum 2, allowing more options and flexibility of usage in containers

## Related issue

[SDS-13341](https://jira.corp.adobe.com/browse/SDS-13341)

## Types of changes

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [ ] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

### CODE REVIEW

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8474614756)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.🚫 drop-shadow-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.🚫 drop-shadow-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-blur
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (15) drop-shadow-x-100, drop-shadow-y-100, drop-shadow-blur-100, drop-shadow-x-200, drop-shadow-y-200, drop-shadow-blur-200, drop-shadow-emphasized-default-x, drop-shadow-emphasized-default-y, drop-shadow-emphasized-default-blur, drop-shadow-emphasized-hover-x, drop-shadow-emphasized-hover-y, drop-shadow-emphasized-hover-blur, drop-shadow-elevated-x, drop-shadow-elevated-y, drop-shadow-elevated-blur
MODIFIED TOKENS: (2) drop-shadow-y, drop-shadow-blur
DEPRECATED TOKENS: (5) drop-shadow-x, drop-shadow-y/desktop, drop-shadow-y/mobile, drop-shadow-blur/desktop, drop-shadow-blur/mobile
CHANGED VALUES: (3) drop-shadow-x, drop-shadow-y/desktop, drop-shadow-blur/desktop
CHANGED SCHEMAS: (3) drop-shadow-x, drop-shadow-y, drop-shadow-blur
```
</p></details>

TEST COMPLETE

**Comment by mrcjhicks** [comment]
**[TESTING spectrum2-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8474614757)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-colors/`
TOKENS STUDIO DATA IS COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.🚫 drop-shadow
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.drop-shadow.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.drop-shadow.100
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/dark.Alias.drop-shadow.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias/light.Alias.drop-shadow.200
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.drop-shadow.emphasized-default
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.drop-shadow.emphasized-hover
UPDATED METADATA - SPECTRUM UUID: spectrum2/alias.Alias.drop-shadow.elevated
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (7) drop-shadow-color-100/dark, drop-shadow-color-100/light, drop-shadow-color-200/dark, drop-shadow-color-200/light, drop-shadow-emphasized-default-color, drop-shadow-emphasized-hover-color, drop-shadow-elevated-color
MODIFIED TOKENS: (1) drop-shadow-color
DEPRECATED TOKENS: (2) drop-shadow-color/light, drop-shadow-color/dark
CHANGED VALUES: (1) drop-shadow-color/light
CHANGED SCHEMAS: (1) drop-shadow-color
```
</p></details>

TEST COMPLETE

**Comment by lynnhao** [comment]
This update also included some new colors in S2/Variables. This is the first time we've done this since we formalized this process, and I wanted to make sure this looks OK to you @nabuhasan @KayiuCarlson @mrcjhicks.

I'm thinking we should potentially leave these out from S2/Color as well, since they are not currently used (styles and variables can't be linked to effects right now in Figma) and might cause confusion to have all these colors. 

@GarthDB I'm also wondering since it would likely make sense for us to remove `drop-shadow-color` in a future release from Figma (now that it's deprecated), if we delete it from Token Studio, will this affect your repo? Should we delete from the Figma files only? 

Screenshot 2024-03-28 at 3 44 10 PM

Screenshot 2024-03-28 at 3 43 37 PM

**Comment by GarthDB** [comment]
I would recommend deleting them in Tokens Studio when we introduce the complex tokens because that will be a breaking change for all the parsers anyway.

**Comment by GarthDB** [comment]
Here's a [link](https://github.com/adobe/spectrum-tokens/discussions/297) to the RFC for more details about the complex tokens for drop shadow.

**Comment by nabuhasan** [comment]
I just shared an update on Slack where I believe that Figma actually supports binding of variables to effects! We may want to reconsider support for this instead of moving with deleting them in Tokens Studio. More in the [slack thread](https://adobedesign.slack.com/archives/GTZ7NSNR0/p1711994594920169?thread_ts=1711666506.206449&cid=GTZ7NSNR0).

**Comment by mrcjhicks** [comment]
**[SYNCING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8530002974)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.🚫 drop-shadow-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.🚫 drop-shadow-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-100
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-x-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-y-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-blur-200
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-default-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-emphasized-hover-blur
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-x
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-y
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.drop-shadow-elevated-blur
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (15) drop-shadow-x-100, drop-shadow-y-100, drop-shadow-blur-100, drop-shadow-x-200, drop-shadow-y-200, drop-shadow-blur-200, drop-shadow-emphasized-default-x, drop-shadow-emphasized-default-y, drop-shadow-emphasized-default-blur, drop-shadow-emphasized-hover-x, drop-shadow-emphasized-hover-y, drop-shadow-emphasized-hover-blur, drop-shadow-elevated-x, drop-shadow-elevated-y, drop-shadow-elevated-blur
MODIFIED TOKENS: (2) drop-shadow-y, drop-shadow-blur
DEPRECATED TOKENS: (5) drop-shadow-x, drop-shadow-y/desktop, drop-shadow-y/mobile, drop-shadow-blur/desktop, drop-shadow-blur/mobile
CHANGED VALUES: (3) drop-shadow-x, drop-shadow-y/desktop, drop-shadow-blur/desktop
CHANGED SCHEMAS: (3) drop-shadow-x, drop-shadow-y, drop-shadow-blur
```
</p></details>

WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout/mobile.json`
WROTE: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/spectrum2/layout/desktop.json`
WROTE: `/spectrum-tokens/packages/tokens/src/layout.json`

SYNC COMPLETE

[Spectrum Tokens Pull Request](https://github.com/adobe/spectrum-tokens/pull/300)
[Tokens Studio Pull Request](https://github.com/adobe/spectrum-tokens-studio-data/pull/87)

**Pull request merged**
